'use client';

import {
  createContext,
  useContext,
  useEffect,
  useState,
  ReactNode,
} from 'react';

export type Language = 'pt' | 'en' | 'fr' | 'ru' | 'es';

const dictionaries = {
  pt: {
    'hero.greeting': 'Olá, eu sou',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Construindo experiências digitais modernas, fluidas e focadas na excelência de produto, do design elegante à arquitetura robusta.',
    'hero.btn.primary': 'Prosseguir',
    'hero.btn.secondary': 'Entrar em Contato',
    'about.title': 'Sobre mim',
    'about.subtitle': 'Engenheiro de Software & Full Stack',
    'about.p1':
      'Desenvolvedor de Software com forte especialização no Front-End (React.js, Next.js, TypeScript) e experiência sólida na arquitetura Back-End (Node.js, Prisma) para a construção de produtos SaaS completos.',
    'about.p2':
      'Tenho experiência em transformar designs do Figma em aplicações web rápidas e escaláveis, unindo código limpo com regras de negócios complexas. Atualmente curso Análise e Desenvolvimento de Sistemas na FATEC.',
    'about.p3':
      'Já atuei em mais de 15 projetos corporativos e trabalhos como freelancer internacional. Faço a ponte entre o design UI/UX e boas soluções técnicas, trabalhando em colaboração direta com Product Owners e QAs em equipes Ágeis, liderando o desenvolvimento técnico de plataformas de ponta a ponta.',
    'about.stats.projects': 'Projetos B2B & B2C',
    'about.stats.years': 'Anos de Exp',
    'gallery.title': 'Galeria',
    'gallery.subtitle': 'Momentos & Bastidores',
    'nav.home': 'Início',
    'nav.about': 'Sobre mim',
    'nav.projects': 'Projetos',
    'nav.courses': 'Cursos',
    'nav.cta': 'Contato',
    'settings.theme': 'Tema',
    'settings.theme.light': 'Modo Claro',
    'settings.theme.dark': 'Modo Escuro',
    'settings.theme.light.short': 'Claro',
    'settings.theme.dark.short': 'Escuro',
    'settings.language': 'Idioma',
    'footer.navigation': 'Navegação',
    'footer.contact': 'Contato',
    'footer.copyright': 'Todos os direitos reservados.',
    'footer.changelog.viewAll': 'Ver todas as versões →',
    'footer.bio': 'Software Engineer & Full Stack — construindo produtos digitais modernos, do design à arquitetura. Focado em React, Next.js e TypeScript.',
    'footer.versions': 'Versões',
    'projects.personal': 'Pessoais',
    'projects.company': 'Empresa',
    'projects.university': 'Faculdade',
    'projects.personal.desc': 'Projetos & Experimentos',
    'projects.company.desc': 'Trabalho Profissional',
    'projects.university.desc': 'Trabalho Acadêmico',
    'projects.title.personal': 'Projetos Pessoais',
    'projects.title.company': 'Projetos de Empresa',
    'projects.title.university': 'Projetos da Faculdade',
    'projects.subtitle.personal': 'Projetos & Experimentos',
    'projects.subtitle.company': 'Trabalhos Profissionais',
    'projects.subtitle.university': 'Trabalhos Acadêmicos',
    'projects.empty': 'Nenhum projeto adicionado ainda. Em breve!',
    'project.elevenlabs.desc': 'Projeto pessoal onde recriei a interface da ElevenLabs utilizando Next.js, React, TypeScript e Styled-Components. Foco em replicar o design, animações e experiência visual completa da plataforma.',
    'project.portfolio.desc': 'Primeiro portfólio pessoal, desenvolvido em 1 mês com responsividade e várias animações. Site com 3 páginas mostrando perfil, projetos, cursos e certificações — basicamente um currículo interativo e mais abrangente.',
    'project.paragrafeado.desc': 'Projeto de navegação em React focado em componentização e roteamento. Interface limpa para exploração de conteúdo com navegação fluida entre páginas.',
    'project.netflix.desc': 'Releitura da Netflix com integração a banco de dados MySQL. Implementação de operações CRUD completas, conexão via PHP e diversas funcionalidades de gerenciamento de conteúdo. Projeto associado à Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Calculadora avançada desenvolvida em linguagem C com mais de 2.500 linhas de código. Projeto colaborativo realizado na Fatec Mogi das Cruzes, cobrindo desde operações básicas até funções matemáticas complexas.',
    'exp.title': 'Experiência',
    'exp.subtitle': 'Stacks & Vivência Profissional',
    'exp.p1': 'Arquitetei e desenvolvi (Front e Back) plataformas SaaS B2B Multi-tenant voltadas para o setor automotivo, conectando concessionárias, lojistas e prestadores de serviço. Implementei lógicas complexas de RBAC, gestão de garagens, leilões, planos de assinatura e integração de pagamentos com Pagar.me.',
    'exp.p2': 'Construí dashboards Admin e B2B complexos para e-commerce, redes sociais e ferramentas internas. Criei sistemas de chat em tempo real com Firebase e WebSockets, além de entregar projetos front-end como freelancer internacional via Upwork para clientes nos EUA.',
    'exp.stats.corporate': 'Projetos Corporativos',
    'exp.stats.fullstack': 'Projeto Corporativo (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certificações',
    'exp.stacks.label': 'Stacks Principais',
    'courses.title': 'Cursos',
    'courses.subtitle': 'Certificações & Aprendizado',
    'courses.count.single': 'curso encontrado',
    'courses.count.plural': 'cursos encontrados',
    'courses.filter.all': 'Todos',
    'courses.filter.organization': 'Organização',
    'courses.filter.skills': 'Competências',
    'courses.hours': 'horas',
    'month.1': 'Janeiro',
    'month.2': 'Fevereiro',
    'month.3': 'Março',
    'month.4': 'Abril',
    'month.5': 'Maio',
    'month.6': 'Junho',
    'month.7': 'Julho',
    'month.8': 'Agosto',
    'month.9': 'Setembro',
    'month.10': 'Outubro',
    'month.11': 'Novembro',
    'month.12': 'Dezembro',
    'date.preposition': ' de ',
    'changelog.title': 'Versões',
    'changelog.description': 'Histórico completo de atualizações e melhorias do portfolio.',
    'changelog.current': 'atual',
    'settings.page.title': 'Configurações',
    'settings.page.subtitle': 'Personalize sua experiência no portfolio.',
    'settings.page.tag': 'Preferências & Sistema',
    'settings.about.title': 'Sobre mim',
    'settings.about.bio': 'Desenvolvedor Full Stack apaixonado por criar experiências digitais modernas e fluidas.',
    'settings.theme.desc': 'Alterne entre os modos claro e escuro.',
    'settings.versions.title': 'Histórico de Versões',
    'settings.wip.section': 'Página Alternativa',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Visualize a versão inicial do portfolio, em construção.',
    'nav.settings': 'Configurações',
    'who.title': 'Quem sou eu?',
    'who.subtitle': 'Desenvolvedor Full Stack',
    'who.bio.p1': 'Sou um desenvolvedor Full Stack com especialização em React, Next.js e TypeScript no Front-End, e Node.js com Prisma no Back-End. Construo produtos SaaS completos, do design à arquitetura.',
    'who.bio.p2': 'Transformo designs Figma em aplicações web rápidas e escaláveis. Atualmente curso Análise e Desenvolvimento de Sistemas na FATEC Mogi das Cruzes.',
    'who.bio.p3': 'Já atuei em mais de 15 projetos corporativos e como freelancer internacional. Faço a ponte entre UI/UX e soluções técnicas, colaborando com POs e QAs em equipes Ágeis.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Tecnologias & Vivência Profissional',
    'nav.timeline': 'Jornada',
    'timeline.page.tag': 'Histórico Profissional',
    'timeline.page.title': 'Minha Jornada',
    'timeline.page.subtitle': 'Uma linha do tempo com os principais marcos da minha carreira como desenvolvedor.',
    'timeline.cat.education': 'Educação',
    'timeline.cat.work': 'Trabalho',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Marco',
    'timeline.freela.title': 'Freelancer Internacional',
    'timeline.freela.subtitle': 'Upwork — Clientes nos EUA',
    'timeline.freela.desc': 'Comecei a atuar como freelancer via Upwork, entregando projetos front-end para clientes americanos. Foco em React, Next.js e TypeScript com entregas rápidas e código de alta qualidade.',
    'timeline.saas.title': 'Plataforma SaaS B2B',
    'timeline.saas.subtitle': 'Full Stack — Setor Automotivo',
    'timeline.saas.desc': 'Arquitetei e desenvolvi uma plataforma SaaS Multi-tenant para o setor automotivo, conectando concessionárias e prestadores. RBAC, gestão de garagens, leilões e integração Pagar.me.',
    'timeline.corporate.title': 'Projetos Corporativos',
    'timeline.corporate.subtitle': 'Dashboards & E-commerce',
    'timeline.corporate.desc': 'Construí dashboards Admin e B2B complexos, sistemas de chat em tempo real com Firebase/WebSockets e interfaces para e-commerce e ferramentas internas.',
    'timeline.portfolio.title': 'Primeiro Portfolio',
    'timeline.portfolio.subtitle': 'Projeto Pessoal',
    'timeline.portfolio.desc': 'Desenvolvi meu primeiro portfolio pessoal em 1 mês, com responsividade completa, animações e 3 páginas mostrando perfil, projetos e certificados.',
    'timeline.fatec.title': 'Início na FATEC',
    'timeline.fatec.subtitle': 'Análise e Desenvolvimento de Sistemas',
    'timeline.fatec.desc': 'Ingressei no curso de ADS na FATEC Mogi das Cruzes, aprofundando conhecimentos em algoritmos, banco de dados, redes e engenharia de software.',
    'timeline.certs.title': 'Certificações',
    'timeline.certs.subtitle': 'Cisco, AWS, Google Cloud & mais',
    'timeline.certs.desc': 'Conquistei mais de 28 certificações em plataformas como Cisco, AWS, Google Cloud e Udemy, cobrindo redes, segurança, cloud e desenvolvimento web.',
    'timeline.firstcode.title': 'Primeiras Linhas de Código',
    'timeline.firstcode.subtitle': 'HTML, CSS & JavaScript',
    'timeline.firstcode.desc': 'Escrevi minhas primeiras linhas de código, aprendendo HTML, CSS e JavaScript. O início de uma jornada apaixonante no desenvolvimento web.',
  },
  en: {
    'hero.greeting': 'Hi, I am',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Building modern, fluid digital experiences focused on product excellence, from elegant design to robust architecture.',
    'hero.btn.primary': 'Continue',
    'hero.btn.secondary': 'Get in Touch',
    'about.title': 'About me',
    'about.subtitle': 'Software Engineer & Full Stack',
    'about.p1':
      'Software Developer with strong specialization in Front-End (React.js, Next.js, TypeScript) and solid experience in Back-End architecture (Node.js, Prisma) for building complete SaaS products.',
    'about.p2':
      'I have experience transforming Figma designs into fast and scalable web applications, uniting clean code with complex business rules. Currently pursuing a degree in Systems Analysis and Development at FATEC.',
    'about.p3':
      'I have worked on more than 15 corporate projects and as an international freelancer. I bridge the gap between UI/UX design and technical solutions, working closely with Product Owners and QAs in Agile teams, leading end-to-end technical development.',
    'about.stats.projects': 'B2B & B2C Projects',
    'about.stats.years': 'Years Exp',
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'Moments & Behind the Scenes',
    'nav.home': 'Home',
    'nav.about': 'About me',
    'nav.projects': 'Projects',
    'nav.courses': 'Courses',
    'nav.cta': 'Contact',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light Mode',
    'settings.theme.dark': 'Dark Mode',
    'settings.theme.light.short': 'Light',
    'settings.theme.dark.short': 'Dark',
    'settings.language': 'Language',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.copyright': 'All rights reserved.',
    'footer.changelog.viewAll': 'View all versions →',
    'footer.bio': 'Software Engineer & Full Stack — building modern digital products, from design to architecture. Focused on React, Next.js and TypeScript.',
    'footer.versions': 'Versions',
    'projects.personal': 'Personal',
    'projects.company': 'Company',
    'projects.university': 'University',
    'projects.personal.desc': 'Projects & Experiments',
    'projects.company.desc': 'Professional Work',
    'projects.university.desc': 'Academic Work',
    'projects.title.personal': 'Personal Projects',
    'projects.title.company': 'Company Projects',
    'projects.title.university': 'University Projects',
    'projects.subtitle.personal': 'Projects & Experiments',
    'projects.subtitle.company': 'Professional Work',
    'projects.subtitle.university': 'Academic Work',
    'projects.empty': 'No projects added yet. Coming soon!',
    'project.elevenlabs.desc': 'Personal project where I recreated the ElevenLabs interface using Next.js, React, TypeScript and Styled-Components. Focused on replicating the design, animations and overall visual experience of the platform.',
    'project.portfolio.desc': 'First personal portfolio, built in 1 month with responsiveness and multiple animations. A 3-page site showcasing profile, projects, courses and certifications — essentially an interactive and comprehensive résumé.',
    'project.paragrafeado.desc': 'React navigation project focused on componentization and routing. Clean interface for content exploration with fluid page navigation.',
    'project.netflix.desc': 'Netflix redesign with MySQL database integration. Full CRUD operations, PHP connection and various content management features. Project associated with Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Advanced calculator built in C with over 2,500 lines of code. Collaborative project at Fatec Mogi das Cruzes, covering basic operations to complex mathematical functions.',
    'exp.title': 'Experience',
    'exp.subtitle': 'Stacks & Professional Background',
    'exp.p1': 'I architected and developed (Front and Back) B2B Multi-tenant SaaS platforms for the automotive sector, connecting dealerships, retailers and service providers. I implemented complex RBAC logic, garage management, auctions, subscription plans and payment integration with Pagar.me.',
    'exp.p2': 'I built complex Admin and B2B dashboards for e-commerce, social networks and internal tools. I created real-time chat systems using Firebase and WebSockets, and delivered front-end projects as an international freelancer via Upwork for US-based clients.',
    'exp.stats.corporate': 'Corporate Projects',
    'exp.stats.fullstack': 'Corporate Project (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certifications',
    'exp.stacks.label': 'Main Stacks',
    'courses.title': 'Courses',
    'courses.subtitle': 'Certifications & Learning',
    'courses.count.single': 'course found',
    'courses.count.plural': 'courses found',
    'courses.filter.all': 'All',
    'courses.filter.organization': 'Organization',
    'courses.filter.skills': 'Skills',
    'courses.hours': 'hours',
    'month.1': 'January',
    'month.2': 'February',
    'month.3': 'March',
    'month.4': 'April',
    'month.5': 'May',
    'month.6': 'June',
    'month.7': 'July',
    'month.8': 'August',
    'month.9': 'September',
    'month.10': 'October',
    'month.11': 'November',
    'month.12': 'December',
    'date.preposition': ' ',
    'changelog.title': 'Versions',
    'changelog.description': 'Complete update and improvement history of the portfolio.',
    'changelog.current': 'current',
    'settings.page.title': 'Settings',
    'settings.page.subtitle': 'Customize your portfolio experience.',
    'settings.page.tag': 'Preferences & System',
    'settings.about.title': 'About me',
    'settings.about.bio': 'Full Stack developer passionate about building modern and fluid digital experiences.',
    'settings.theme.desc': 'Switch between light and dark modes.',
    'settings.versions.title': 'Version History',
    'settings.wip.section': 'Alternative Page',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'View the initial version of the portfolio, under construction.',
    'nav.settings': 'Settings',
    'who.title': 'Who am I?',
    'who.subtitle': 'Full Stack Developer',
    'who.bio.p1': 'I am a Full Stack developer with expertise in React, Next.js and TypeScript on the Front-End, and Node.js with Prisma on the Back-End. I build complete SaaS products, from design to architecture.',
    'who.bio.p2': 'I transform Figma designs into fast and scalable web applications. Currently pursuing a degree in Systems Analysis and Development at FATEC Mogi das Cruzes.',
    'who.bio.p3': 'I have worked on over 15 corporate projects and as an international freelancer. I bridge UI/UX and technical solutions, collaborating with POs and QAs in Agile teams.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Technologies & Professional Background',
    'nav.timeline': 'Journey',
    'timeline.page.tag': 'Professional History',
    'timeline.page.title': 'My Journey',
    'timeline.page.subtitle': 'A timeline of the main milestones in my career as a developer.',
    'timeline.cat.education': 'Education',
    'timeline.cat.work': 'Work',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Milestone',
    'timeline.freela.title': 'International Freelancer',
    'timeline.freela.subtitle': 'Upwork — US Clients',
    'timeline.freela.desc': 'Started freelancing on Upwork, delivering front-end projects for American clients. Focus on React, Next.js and TypeScript with fast deliveries and high-quality code.',
    'timeline.saas.title': 'SaaS B2B Platform',
    'timeline.saas.subtitle': 'Full Stack — Automotive Sector',
    'timeline.saas.desc': 'Architected and developed a Multi-tenant SaaS platform for the automotive sector, connecting dealerships and service providers. RBAC, garage management, auctions and Pagar.me payment integration.',
    'timeline.corporate.title': 'Corporate Projects',
    'timeline.corporate.subtitle': 'Dashboards & E-commerce',
    'timeline.corporate.desc': 'Built complex Admin and B2B dashboards, real-time chat systems with Firebase/WebSockets, and interfaces for e-commerce and internal tools.',
    'timeline.portfolio.title': 'First Portfolio',
    'timeline.portfolio.subtitle': 'Personal Project',
    'timeline.portfolio.desc': 'Developed my first personal portfolio in 1 month, with full responsiveness, animations and 3 pages showcasing profile, projects and certifications.',
    'timeline.fatec.title': 'Started at FATEC',
    'timeline.fatec.subtitle': 'Systems Analysis and Development',
    'timeline.fatec.desc': 'Enrolled in the Systems Analysis and Development program at FATEC Mogi das Cruzes, deepening knowledge in algorithms, databases, networking and software engineering.',
    'timeline.certs.title': 'Certifications',
    'timeline.certs.subtitle': 'Cisco, AWS, Google Cloud & more',
    'timeline.certs.desc': 'Earned over 28 certifications on platforms like Cisco, AWS, Google Cloud and Udemy, covering networking, security, cloud and web development.',
    'timeline.firstcode.title': 'First Lines of Code',
    'timeline.firstcode.subtitle': 'HTML, CSS & JavaScript',
    'timeline.firstcode.desc': 'Wrote my first lines of code, learning HTML, CSS and JavaScript. The beginning of a passionate journey into web development.',
  },
  fr: {
    'hero.greeting': 'Bonjour, je suis',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Création d\'expériences numériques modernes, fluides et axées sur l\'excellence produit, du design élégant à l\'architecture robuste.',
    'hero.btn.primary': 'Continuer',
    'hero.btn.secondary': 'Me Contacter',
    'about.title': 'À propos',
    'about.subtitle': 'Ingénieur Logiciel & Full Stack',
    'about.p1':
      'Développeur logiciel avec une forte spécialisation en Front-End (React.js, Next.js, TypeScript) et une expérience solide en architecture Back-End (Node.js, Prisma) pour la construction de produits SaaS complets.',
    'about.p2':
      'J\'ai de l\'expérience dans la transformation de designs Figma en applications web rapides et évolutives, alliant code propre et règles métier complexes. Actuellement en formation en Analyse et Développement de Systèmes à la FATEC.',
    'about.p3':
      'J\'ai travaillé sur plus de 15 projets d\'entreprise et en tant que freelance international. Je fais le pont entre le design UI/UX et les solutions techniques, en collaboration directe avec les Product Owners et QAs dans des équipes Agiles, pilotant le développement technique de bout en bout.',
    'about.stats.projects': 'Projets B2B & B2C',
    'about.stats.years': 'Ans d\'Exp',
    'gallery.title': 'Galerie',
    'gallery.subtitle': 'Moments & Coulisses',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.projects': 'Projets',
    'nav.courses': 'Formations',
    'nav.cta': 'Contact',
    'settings.theme': 'Thème',
    'settings.theme.light': 'Mode Clair',
    'settings.theme.dark': 'Mode Sombre',
    'settings.theme.light.short': 'Clair',
    'settings.theme.dark.short': 'Sombre',
    'settings.language': 'Langue',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.copyright': 'Tous droits réservés.',
    'footer.changelog.viewAll': 'Voir toutes les versions →',
    'footer.bio': 'Software Engineer & Full Stack — création de produits numériques modernes, du design à l\'architecture. Spécialisé en React, Next.js et TypeScript.',
    'footer.versions': 'Versions',
    'projects.personal': 'Personnels',
    'projects.company': 'Entreprise',
    'projects.university': 'Université',
    'projects.personal.desc': 'Projets & Expériences',
    'projects.company.desc': 'Travail Professionnel',
    'projects.university.desc': 'Travail Académique',
    'projects.title.personal': 'Projets Personnels',
    'projects.title.company': 'Projets d\'Entreprise',
    'projects.title.university': 'Projets Universitaires',
    'projects.subtitle.personal': 'Projets & Expériences',
    'projects.subtitle.company': 'Travail Professionnel',
    'projects.subtitle.university': 'Travail Académique',
    'projects.empty': 'Aucun projet ajouté pour le moment. Bientôt disponible !',
    'project.elevenlabs.desc': 'Projet personnel où j\'ai recréé l\'interface ElevenLabs avec Next.js, React, TypeScript et Styled-Components. Axé sur la reproduction du design, des animations et de l\'expérience visuelle de la plateforme.',
    'project.portfolio.desc': 'Premier portfolio personnel, développé en 1 mois avec responsivité et animations multiples. Un site de 3 pages présentant profil, projets, formations et certifications — un CV interactif et complet.',
    'project.paragrafeado.desc': 'Projet de navigation React axé sur la composantisation et le routage. Interface épurée pour l\'exploration de contenu avec navigation fluide entre les pages.',
    'project.netflix.desc': 'Refonte de Netflix avec intégration MySQL. Opérations CRUD complètes, connexion PHP et fonctionnalités de gestion de contenu. Projet associé à Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Calculatrice avancée développée en C avec plus de 2 500 lignes de code. Projet collaboratif à Fatec Mogi das Cruzes, couvrant des opérations basiques aux fonctions mathématiques complexes.',
    'exp.title': 'Expérience',
    'exp.subtitle': 'Stacks & Parcours Professionnel',
    'exp.p1': 'J\'ai conçu et développé (Front et Back) des plateformes SaaS B2B Multi-tenant pour le secteur automobile, connectant concessionnaires, détaillants et prestataires. J\'ai implémenté des logiques RBAC complexes, gestion de garages, enchères, abonnements et intégration de paiements avec Pagar.me.',
    'exp.p2': 'J\'ai construit des dashboards Admin et B2B complexes pour l\'e-commerce, les réseaux sociaux et les outils internes. J\'ai créé des systèmes de chat en temps réel avec Firebase et WebSockets, et livré des projets front-end en tant que freelance international via Upwork pour des clients américains.',
    'exp.stats.corporate': 'Projets Entreprise',
    'exp.stats.fullstack': 'Projet Entreprise (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certifications',
    'exp.stacks.label': 'Stacks Principales',
    'courses.title': 'Formations',
    'courses.subtitle': 'Certifications & Apprentissage',
    'courses.count.single': 'formation trouvée',
    'courses.count.plural': 'formations trouvées',
    'courses.filter.all': 'Tous',
    'courses.filter.organization': 'Organisation',
    'courses.filter.skills': 'Compétences',
    'courses.hours': 'heures',
    'month.1': 'Janvier',
    'month.2': 'Février',
    'month.3': 'Mars',
    'month.4': 'Avril',
    'month.5': 'Mai',
    'month.6': 'Juin',
    'month.7': 'Juillet',
    'month.8': 'Août',
    'month.9': 'Septembre',
    'month.10': 'Octobre',
    'month.11': 'Novembre',
    'month.12': 'Décembre',
    'date.preposition': ' ',
    'changelog.title': 'Versions',
    'changelog.description': 'Historique complet des mises à jour et améliorations du portfolio.',
    'changelog.current': 'actuel',
    'settings.page.title': 'Paramètres',
    'settings.page.subtitle': 'Personnalisez votre expérience sur le portfolio.',
    'settings.page.tag': 'Préférences & Système',
    'settings.about.title': 'À propos',
    'settings.about.bio': 'Développeur Full Stack passionné par la création d\'expériences numériques modernes et fluides.',
    'settings.theme.desc': 'Basculez entre les modes clair et sombre.',
    'settings.versions.title': 'Historique des Versions',
    'settings.wip.section': 'Page Alternative',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Voir la version initiale du portfolio, en construction.',
    'nav.settings': 'Paramètres',
    'who.title': 'Qui suis-je ?',
    'who.subtitle': 'Développeur Full Stack',
    'who.bio.p1': 'Je suis un développeur Full Stack spécialisé en React, Next.js et TypeScript côté Front-End, et Node.js avec Prisma côté Back-End. Je construis des produits SaaS complets, du design à l\'architecture.',
    'who.bio.p2': 'Je transforme des designs Figma en applications web rapides et évolutives. Actuellement en formation en Analyse et Développement de Systèmes à la FATEC Mogi das Cruzes.',
    'who.bio.p3': 'J\'ai travaillé sur plus de 15 projets d\'entreprise et en tant que freelance international. Je fais le pont entre UI/UX et solutions techniques, en collaboration avec POs et QAs en équipes Agiles.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Technologies & Parcours Professionnel',
    'nav.timeline': 'Parcours',
    'timeline.page.tag': 'Historique Professionnel',
    'timeline.page.title': 'Mon Parcours',
    'timeline.page.subtitle': 'Une chronologie des principaux jalons de ma carrière en tant que développeur.',
    'timeline.cat.education': 'Éducation',
    'timeline.cat.work': 'Travail',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Jalon',
    'timeline.freela.title': 'Freelance International',
    'timeline.freela.subtitle': 'Upwork — Clients américains',
    'timeline.freela.desc': 'J\'ai commencé à travailler en freelance via Upwork, livrant des projets front-end pour des clients américains. Focus sur React, Next.js et TypeScript.',
    'timeline.saas.title': 'Plateforme SaaS B2B',
    'timeline.saas.subtitle': 'Full Stack — Secteur Automobile',
    'timeline.saas.desc': 'Architecturé et développé une plateforme SaaS Multi-tenant pour le secteur automobile. RBAC, gestion de garages, enchères et intégration de paiements.',
    'timeline.corporate.title': 'Projets d\'Entreprise',
    'timeline.corporate.subtitle': 'Tableaux de bord & E-commerce',
    'timeline.corporate.desc': 'Construit des tableaux de bord Admin et B2B complexes, des systèmes de chat en temps réel avec Firebase/WebSockets et des interfaces e-commerce.',
    'timeline.portfolio.title': 'Premier Portfolio',
    'timeline.portfolio.subtitle': 'Projet Personnel',
    'timeline.portfolio.desc': 'Développé mon premier portfolio personnel en 1 mois, avec responsivité complète, animations et 3 pages.',
    'timeline.fatec.title': 'Début à la FATEC',
    'timeline.fatec.subtitle': 'Analyse et Développement de Systèmes',
    'timeline.fatec.desc': 'Inscription au programme d\'Analyse et Développement de Systèmes à la FATEC Mogi das Cruzes.',
    'timeline.certs.title': 'Certifications',
    'timeline.certs.subtitle': 'Cisco, AWS, Google Cloud & plus',
    'timeline.certs.desc': 'Obtenu plus de 28 certifications sur des plateformes comme Cisco, AWS, Google Cloud et Udemy.',
    'timeline.firstcode.title': 'Premières Lignes de Code',
    'timeline.firstcode.subtitle': 'HTML, CSS & JavaScript',
    'timeline.firstcode.desc': 'J\'ai écrit mes premières lignes de code en HTML, CSS et JavaScript. Le début d\'un parcours passionnant.',
  },
  ru: {
    'hero.greeting': 'Привет, я',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Создание современных, плавных цифровых решений с фокусом на качество продукта — от элегантного дизайна до надёжной архитектуры.',
    'hero.btn.primary': 'Продолжить',
    'hero.btn.secondary': 'Связаться',
    'about.title': 'Обо мне',
    'about.subtitle': 'Инженер-программист & Full Stack',
    'about.p1':
      'Разработчик ПО с сильной специализацией во Front-End (React.js, Next.js, TypeScript) и солидным опытом в архитектуре Back-End (Node.js, Prisma) для создания полноценных SaaS-продуктов.',
    'about.p2':
      'Имею опыт преобразования дизайнов Figma в быстрые и масштабируемые веб-приложения, сочетая чистый код со сложной бизнес-логикой. В настоящее время учусь на факультете анализа и разработки систем в FATEC.',
    'about.p3':
      'Работал над более чем 15 корпоративными проектами и в качестве международного фрилансера. Объединяю UI/UX дизайн и технические решения, тесно сотрудничая с Product Owner-ами и QA в Agile-командах, руководя сквозной технической разработкой.',
    'about.stats.projects': 'B2B и B2C Проекты',
    'about.stats.years': 'Лет Опыта',
    'gallery.title': 'Галерея',
    'gallery.subtitle': 'Моменты и Закулисье',
    'nav.home': 'Главная',
    'nav.about': 'Обо мне',
    'nav.projects': 'Проекты',
    'nav.courses': 'Курсы',
    'nav.cta': 'Контакт',
    'settings.theme': 'Тема',
    'settings.theme.light': 'Светлый режим',
    'settings.theme.dark': 'Тёмный режим',
    'settings.theme.light.short': 'Светлая',
    'settings.theme.dark.short': 'Тёмная',
    'settings.language': 'Язык',
    'footer.navigation': 'Навигация',
    'footer.contact': 'Контакт',
    'footer.copyright': 'Все права защищены.',
    'footer.changelog.viewAll': 'Все версии →',
    'footer.bio': 'Software Engineer & Full Stack — создание современных цифровых продуктов, от дизайна до архитектуры. Специализация: React, Next.js и TypeScript.',
    'footer.versions': 'Версии',
    'projects.personal': 'Личные',
    'projects.company': 'Компания',
    'projects.university': 'Университет',
    'projects.personal.desc': 'Проекты и Эксперименты',
    'projects.company.desc': 'Профессиональная Работа',
    'projects.university.desc': 'Учебная Работа',
    'projects.title.personal': 'Личные Проекты',
    'projects.title.company': 'Проекты Компании',
    'projects.title.university': 'Университетские Проекты',
    'projects.subtitle.personal': 'Проекты и Эксперименты',
    'projects.subtitle.company': 'Профессиональная Работа',
    'projects.subtitle.university': 'Учебная Работа',
    'projects.empty': 'Проекты ещё не добавлены. Скоро будут!',
    'project.elevenlabs.desc': 'Личный проект, в котором я воссоздал интерфейс ElevenLabs с использованием Next.js, React, TypeScript и Styled-Components. Фокус на воспроизведении дизайна, анимаций и визуального опыта платформы.',
    'project.portfolio.desc': 'Первое личное портфолио, созданное за 1 месяц с адаптивностью и множеством анимаций. Сайт из 3 страниц с профилем, проектами, курсами и сертификатами — интерактивное и подробное резюме.',
    'project.paragrafeado.desc': 'React-проект навигации с фокусом на компонентизацию и маршрутизацию. Чистый интерфейс для просмотра контента с плавной навигацией между страницами.',
    'project.netflix.desc': 'Редизайн Netflix с интеграцией базы данных MySQL. Полные CRUD-операции, подключение через PHP и различные функции управления контентом. Проект при Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Продвинутый калькулятор на языке C, более 2 500 строк кода. Совместный проект в Fatec Mogi das Cruzes, от базовых операций до сложных математических функций.',
    'exp.title': 'Опыт',
    'exp.subtitle': 'Стек и Профессиональный Путь',
    'exp.p1': 'Спроектировал и разработал (Front и Back) мульти-тенантные B2B SaaS-платформы для автомобильного сектора, связывающие дилеров, розничных продавцов и сервис-провайдеров. Реализовал сложную логику RBAC, управление гаражами, аукционы, подписки и интеграцию платежей с Pagar.me.',
    'exp.p2': 'Создавал сложные Admin и B2B дашборды для e-commerce, социальных сетей и внутренних инструментов. Разработал системы чата в реальном времени с Firebase и WebSockets, выполнял front-end проекты как международный фрилансер через Upwork для клиентов из США.',
    'exp.stats.corporate': 'Корпоративные Проекты',
    'exp.stats.fullstack': 'Корпоративный Проект (FullStack)',
    'exp.stats.commits': 'Коммиты',
    'exp.stats.certifications': 'Сертификаты',
    'exp.stacks.label': 'Основные Стеки',
    'courses.title': 'Курсы',
    'courses.subtitle': 'Сертификаты и Обучение',
    'courses.count.single': 'курс найден',
    'courses.count.plural': 'курсов найдено',
    'courses.filter.all': 'Все',
    'courses.filter.organization': 'Организация',
    'courses.filter.skills': 'Навыки',
    'courses.hours': 'часов',
    'month.1': 'Январь',
    'month.2': 'Февраль',
    'month.3': 'Март',
    'month.4': 'Апрель',
    'month.5': 'Май',
    'month.6': 'Июнь',
    'month.7': 'Июль',
    'month.8': 'Август',
    'month.9': 'Сентябрь',
    'month.10': 'Октябрь',
    'month.11': 'Ноябрь',
    'month.12': 'Декабрь',
    'date.preposition': ' ',
    'changelog.title': 'Версии',
    'changelog.description': 'Полная история обновлений и улучшений портфолио.',
    'changelog.current': 'текущая',
    'settings.page.title': 'Настройки',
    'settings.page.subtitle': 'Настройте своё взаимодействие с портфолио.',
    'settings.page.tag': 'Настройки и Система',
    'settings.about.title': 'Обо мне',
    'settings.about.bio': 'Full Stack разработчик, увлечённый созданием современных и плавных цифровых решений.',
    'settings.theme.desc': 'Переключайтесь между светлой и тёмной темой.',
    'settings.versions.title': 'История Версий',
    'settings.wip.section': 'Альтернативная Страница',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Посмотреть начальную версию портфолио в разработке.',
    'nav.settings': 'Настройки',
    'who.title': 'Кто я?',
    'who.subtitle': 'Full Stack разработчик',
    'who.bio.p1': 'Я Full Stack разработчик с опытом в React, Next.js и TypeScript на фронтенде, и Node.js с Prisma на бэкенде. Создаю полные SaaS-продукты — от дизайна до архитектуры.',
    'who.bio.p2': 'Превращаю Figma-дизайны в быстрые и масштабируемые веб-приложения. Обучаюсь на факультете анализа и разработки систем в FATEC Mogi das Cruzes.',
    'who.bio.p3': 'Работал над более 15 корпоративными проектами и как международный фрилансер. Связываю UI/UX и технические решения, сотрудничая с PO и QA в Agile-командах.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Технологии & Профессиональный Опыт',
    'nav.timeline': 'Путь',
    'timeline.page.tag': 'Профессиональная История',
    'timeline.page.title': 'Мой Путь',
    'timeline.page.subtitle': 'Хронология основных этапов моей карьеры разработчика.',
    'timeline.cat.education': 'Образование',
    'timeline.cat.work': 'Работа',
    'timeline.cat.freelance': 'Фриланс',
    'timeline.cat.milestone': 'Веха',
    'timeline.freela.title': 'Международный фрилансер',
    'timeline.freela.subtitle': 'Upwork — Клиенты из США',
    'timeline.freela.desc': 'Начал фрилансить на Upwork, выполняя фронтенд-проекты для американских клиентов. Фокус на React, Next.js и TypeScript.',
    'timeline.saas.title': 'Платформа SaaS B2B',
    'timeline.saas.subtitle': 'Full Stack — Автомобильный сектор',
    'timeline.saas.desc': 'Спроектировал и разработал Multi-tenant SaaS платформу для автомобильного сектора. RBAC, управление гаражами, аукционы и интеграция платежей.',
    'timeline.corporate.title': 'Корпоративные Проекты',
    'timeline.corporate.subtitle': 'Дашборды & E-commerce',
    'timeline.corporate.desc': 'Создал сложные Admin и B2B дашборды, системы чатов в реальном времени с Firebase/WebSockets.',
    'timeline.portfolio.title': 'Первое Портфолио',
    'timeline.portfolio.subtitle': 'Личный проект',
    'timeline.portfolio.desc': 'Разработал первое персональное портфолио за 1 месяц с полной адаптивностью и анимациями.',
    'timeline.fatec.title': 'Начало в FATEC',
    'timeline.fatec.subtitle': 'Анализ и Разработка Систем',
    'timeline.fatec.desc': 'Поступил на программу Анализа и Разработки Систем в FATEC Mogi das Cruzes.',
    'timeline.certs.title': 'Сертификации',
    'timeline.certs.subtitle': 'Cisco, AWS, Google Cloud & др.',
    'timeline.certs.desc': 'Получил более 28 сертификатов на платформах Cisco, AWS, Google Cloud и Udemy.',
    'timeline.firstcode.title': 'Первые Строки Кода',
    'timeline.firstcode.subtitle': 'HTML, CSS & JavaScript',
    'timeline.firstcode.desc': 'Написал первые строки кода, изучая HTML, CSS и JavaScript. Начало увлекательного пути в веб-разработку.',
  },
  es: {
    'hero.greeting': 'Hola, soy',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Construyendo experiencias digitales modernas, fluidas y centradas en la excelencia del producto, del diseño elegante a la arquitectura robusta.',
    'hero.btn.primary': 'Continuar',
    'hero.btn.secondary': 'Contáctame',
    'about.title': 'Sobre mí',
    'about.subtitle': 'Ingeniero de Software & Full Stack',
    'about.p1':
      'Desarrollador de Software con fuerte especialización en Front-End (React.js, Next.js, TypeScript) y experiencia sólida en arquitectura Back-End (Node.js, Prisma) para la construcción de productos SaaS completos.',
    'about.p2':
      'Transformo diseños de Figma en aplicaciones web rápidas y escalables, uniendo código limpio con reglas de negocio complejas. Actualmente estudio Análisis y Desarrollo de Sistemas en la FATEC Mogi das Cruzes.',
    'about.p3':
      'He trabajado en más de 15 proyectos corporativos y como freelancer internacional. Hago de puente entre el diseño UI/UX y las soluciones técnicas, colaborando con Product Owners y QAs en equipos Ágiles.',
    'about.stats.projects': 'Proyectos B2B & B2C',
    'about.stats.years': 'Años de Exp',
    'gallery.title': 'Galería',
    'gallery.subtitle': 'Momentos & Backstage',
    'nav.home': 'Inicio',
    'nav.about': 'Sobre mí',
    'nav.projects': 'Proyectos',
    'nav.courses': 'Cursos',
    'nav.cta': 'Contacto',
    'settings.theme': 'Tema',
    'settings.theme.light': 'Modo Claro',
    'settings.theme.dark': 'Modo Oscuro',
    'settings.theme.light.short': 'Claro',
    'settings.theme.dark.short': 'Oscuro',
    'settings.language': 'Idioma',
    'footer.navigation': 'Navegación',
    'footer.contact': 'Contacto',
    'footer.copyright': 'Todos los derechos reservados.',
    'footer.changelog.viewAll': 'Ver todas las versiones →',
    'footer.bio': 'Software Engineer & Full Stack — construyendo productos digitales modernos, del diseño a la arquitectura. Enfocado en React, Next.js y TypeScript.',
    'footer.versions': 'Versiones',
    'projects.personal': 'Personales',
    'projects.company': 'Empresa',
    'projects.university': 'Universidad',
    'projects.personal.desc': 'Proyectos & Experimentos',
    'projects.company.desc': 'Trabajo Profesional',
    'projects.university.desc': 'Trabajo Académico',
    'projects.title.personal': 'Proyectos Personales',
    'projects.title.company': 'Proyectos de Empresa',
    'projects.title.university': 'Proyectos Universitarios',
    'projects.subtitle.personal': 'Proyectos & Experimentos',
    'projects.subtitle.company': 'Trabajos Profesionales',
    'projects.subtitle.university': 'Trabajos Académicos',
    'projects.empty': 'Ningún proyecto añadido aún. ¡Próximamente!',
    'project.elevenlabs.desc': 'Proyecto personal donde recreé la interfaz de ElevenLabs usando Next.js, React, TypeScript y Styled-Components. Enfocado en replicar el diseño, animaciones y experiencia visual completa de la plataforma.',
    'project.portfolio.desc': 'Primer portfolio personal, desarrollado en 1 mes con responsividad y varias animaciones. Sitio con 3 páginas mostrando perfil, proyectos, cursos y certificaciones.',
    'project.paragrafeado.desc': 'Proyecto de navegación en React centrado en componentización y enrutamiento. Interfaz limpia para exploración de contenido con navegación fluida entre páginas.',
    'project.netflix.desc': 'Reinterpretación de Netflix con integración a base de datos MySQL. Implementación de operaciones CRUD completas, conexión vía PHP y diversas funcionalidades de gestión de contenido.',
    'project.calculadora.desc': 'Calculadora avanzada desarrollada en lenguaje C con más de 2.500 líneas de código. Proyecto colaborativo realizado en la Fatec Mogi das Cruzes.',
    'exp.title': 'Experiencia',
    'exp.subtitle': 'Stacks & Vivencia Profesional',
    'exp.p1': 'Diseñé y desarrollé (Front y Back) plataformas SaaS B2B Multi-tenant para el sector automotriz, conectando concesionarios, comerciantes y proveedores de servicios. Implementé lógicas complejas de RBAC, gestión de garajes, subastas, planes de suscripción e integración de pagos con Pagar.me.',
    'exp.p2': 'Construí dashboards Admin y B2B complejos para e-commerce, redes sociales y herramientas internas. Creé sistemas de chat en tiempo real con Firebase y WebSockets, además de entregar proyectos front-end como freelancer internacional vía Upwork para clientes en EE.UU.',
    'exp.stats.corporate': 'Proyectos Corporativos',
    'exp.stats.fullstack': 'Proyecto Corporativo (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certificaciones',
    'exp.stacks.label': 'Stacks Principales',
    'courses.title': 'Cursos',
    'courses.subtitle': 'Certificaciones & Aprendizaje',
    'courses.count.single': 'curso encontrado',
    'courses.count.plural': 'cursos encontrados',
    'courses.filter.all': 'Todos',
    'courses.filter.organization': 'Organización',
    'courses.filter.skills': 'Competencias',
    'courses.hours': 'horas',
    'month.1': 'Enero',
    'month.2': 'Febrero',
    'month.3': 'Marzo',
    'month.4': 'Abril',
    'month.5': 'Mayo',
    'month.6': 'Junio',
    'month.7': 'Julio',
    'month.8': 'Agosto',
    'month.9': 'Septiembre',
    'month.10': 'Octubre',
    'month.11': 'Noviembre',
    'month.12': 'Diciembre',
    'date.preposition': ' de ',
    'changelog.title': 'Versiones',
    'changelog.description': 'Historial completo de actualizaciones y mejoras del portfolio.',
    'changelog.current': 'actual',
    'settings.page.title': 'Configuración',
    'settings.page.subtitle': 'Personaliza tu experiencia en el portfolio.',
    'settings.page.tag': 'Preferencias y Sistema',
    'settings.about.title': 'Sobre mí',
    'settings.about.bio': 'Desarrollador Full Stack apasionado por crear experiencias digitales modernas y fluidas.',
    'settings.theme.desc': 'Alterna entre los modos claro y oscuro.',
    'settings.versions.title': 'Historial de Versiones',
    'settings.wip.section': 'Página Alternativa',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Visualiza la versión inicial del portfolio, en construcción.',
    'nav.settings': 'Configuración',
    'who.title': '¿Quién soy?',
    'who.subtitle': 'Desarrollador Full Stack',
    'who.bio.p1': 'Soy un desarrollador Full Stack con especialización en React, Next.js y TypeScript en el Front-End, y Node.js con Prisma en el Back-End. Construyo productos SaaS completos, desde el diseño hasta la arquitectura.',
    'who.bio.p2': 'Transformo diseños de Figma en aplicaciones web rápidas y escalables. Actualmente estudio Análisis y Desarrollo de Sistemas en la FATEC Mogi das Cruzes.',
    'who.bio.p3': 'He trabajado en más de 15 proyectos corporativos y como freelancer internacional. Hago de puente entre UI/UX y soluciones técnicas, colaborando con POs y QAs en equipos Ágiles.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Tecnologías & Experiencia Profesional',
    'nav.timeline': 'Trayectoria',
    'timeline.page.tag': 'Historial Profesional',
    'timeline.page.title': 'Mi Trayectoria',
    'timeline.page.subtitle': 'Una línea de tiempo con los principales hitos de mi carrera como desarrollador.',
    'timeline.cat.education': 'Educación',
    'timeline.cat.work': 'Trabajo',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Hito',
    'timeline.freela.title': 'Freelancer Internacional',
    'timeline.freela.subtitle': 'Upwork — Clientes en EE.UU.',
    'timeline.freela.desc': 'Comencé a trabajar como freelancer en Upwork, entregando proyectos front-end para clientes americanos. Enfoque en React, Next.js y TypeScript.',
    'timeline.saas.title': 'Plataforma SaaS B2B',
    'timeline.saas.subtitle': 'Full Stack — Sector Automotriz',
    'timeline.saas.desc': 'Diseñé y desarrollé una plataforma SaaS Multi-tenant para el sector automotriz. RBAC, gestión de garajes, subastas e integración de pagos.',
    'timeline.corporate.title': 'Proyectos Corporativos',
    'timeline.corporate.subtitle': 'Dashboards & E-commerce',
    'timeline.corporate.desc': 'Construí dashboards Admin y B2B complejos, sistemas de chat en tiempo real con Firebase/WebSockets e interfaces de e-commerce.',
    'timeline.portfolio.title': 'Primer Portfolio',
    'timeline.portfolio.subtitle': 'Proyecto Personal',
    'timeline.portfolio.desc': 'Desarrollé mi primer portfolio personal en 1 mes, con responsividad completa, animaciones y 3 páginas.',
    'timeline.fatec.title': 'Inicio en la FATEC',
    'timeline.fatec.subtitle': 'Análisis y Desarrollo de Sistemas',
    'timeline.fatec.desc': 'Ingresé al programa de Análisis y Desarrollo de Sistemas en la FATEC Mogi das Cruzes.',
    'timeline.certs.title': 'Certificaciones',
    'timeline.certs.subtitle': 'Cisco, AWS, Google Cloud & más',
    'timeline.certs.desc': 'Obtuve más de 28 certificaciones en plataformas como Cisco, AWS, Google Cloud y Udemy.',
    'timeline.firstcode.title': 'Primeras Líneas de Código',
    'timeline.firstcode.subtitle': 'HTML, CSS & JavaScript',
    'timeline.firstcode.desc': 'Escribí mis primeras líneas de código, aprendiendo HTML, CSS y JavaScript. El comienzo de un apasionante viaje.',
  },
} as const;

type DictionaryKeys = keyof typeof dictionaries.pt;

const getTranslation = (lang: Language, key: DictionaryKeys) => {
  return dictionaries[lang][key] || key;
};

interface LanguageContextData {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: DictionaryKeys) => string;
}

const LanguageContext = createContext<LanguageContextData>({
  language: 'pt',
  toggleLanguage: () => {},
  setLanguage: () => {},
  t: (key: DictionaryKeys) => getTranslation('pt', key),
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pt');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('@Portfolio:lang') as Language;
    if (savedLanguage) {
      setLanguage(savedLanguage);
    } else {
      const nav = navigator.language;
      if (nav.startsWith('fr')) setLanguage('fr');
      else if (nav.startsWith('ru')) setLanguage('ru');
      else if (nav.startsWith('es')) setLanguage('es');
      else if (nav.startsWith('en')) setLanguage('en');
      else setLanguage('pt');
    }
  }, []);

  const toggleLanguage = () => {
    const newLang = language === 'pt' ? 'en' : 'pt';
    setLanguage(newLang);
    localStorage.setItem('@Portfolio:lang', newLang);
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('@Portfolio:lang', lang);
  };

  const t = (key: DictionaryKeys) => getTranslation(language, key);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
