'use client';

import {
  createContext,
  useContext,
  useEffect,
  useState,
  ReactNode,
} from 'react';

export type Language = 'pt' | 'en' | 'fr' | 'ru' | 'es';

const dictionaries = {
  pt: {
    'hero.greeting': 'Olá, eu sou',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Construindo experiências digitais modernas, fluidas e focadas na excelência de produto, do design elegante à arquitetura robusta.',
    'hero.btn.primary': 'Prosseguir',
    'hero.btn.secondary': 'Entrar em Contato',
    'about.title': 'Sobre mim',
    'about.subtitle': 'Engenheiro de Software & Full Stack',
    'about.p1':
      'Desenvolvedor de Software com forte especialização no Front-End (React.js, Next.js, TypeScript) e experiência sólida na arquitetura Back-End (Node.js, Prisma) para a construção de produtos SaaS completos.',
    'about.p2':
      'Tenho experiência em transformar designs do Figma em aplicações web rápidas e escaláveis, unindo código limpo com regras de negócios complexas. Atualmente curso Análise e Desenvolvimento de Sistemas na FATEC.',
    'about.p3':
      'Já atuei em mais de 15 projetos corporativos e trabalhos como freelancer internacional. Faço a ponte entre o design UI/UX e boas soluções técnicas, trabalhando em colaboração direta com Product Owners e QAs em equipes Ágeis, liderando o desenvolvimento técnico de plataformas de ponta a ponta.',
    'about.stats.projects': 'Projetos B2B & B2C',
    'about.stats.years': 'Anos de Exp',
    'gallery.title': 'Galeria',
    'gallery.subtitle': 'Momentos & Bastidores',
    'nav.home': 'Início',
    'nav.about': 'Sobre mim',
    'nav.projects': 'Projetos',
    'nav.portfolio': 'Portfólio',
    'nav.courses': 'Cursos',
    'nav.cta': 'Contato',
    'settings.theme': 'Tema',
    'settings.theme.light': 'Modo Claro',
    'settings.theme.dark': 'Modo Escuro',
    'settings.theme.light.short': 'Claro',
    'settings.theme.dark.short': 'Escuro',
    'settings.language': 'Idioma',
    'footer.navigation': 'Navegação',
    'footer.contact': 'Contato',
    'footer.copyright': 'Todos os direitos reservados.',
    'footer.changelog.viewAll': 'Ver todas as versões →',
    'footer.bio': 'Software Engineer & Full Stack — construindo produtos digitais modernos, do design à arquitetura. Focado em React, Next.js e TypeScript.',
    'footer.versions': 'Versões',
    'projects.personal': 'Pessoais',
    'projects.company': 'Empresa',
    'projects.university': 'Faculdade',
    'projects.personal.desc': 'Projetos & Experimentos',
    'projects.company.desc': 'Trabalho Profissional',
    'projects.university.desc': 'Trabalho Acadêmico',
    'projects.title.personal': 'Projetos Pessoais',
    'projects.title.company': 'Projetos de Empresa',
    'projects.title.university': 'Projetos da Faculdade',
    'projects.subtitle.personal': 'Projetos & Experimentos',
    'projects.subtitle.company': 'Trabalhos Profissionais',
    'projects.subtitle.university': 'Trabalhos Acadêmicos',
    'projects.empty': 'Nenhum projeto adicionado ainda. Em breve!',
    'project.elevenlabs.desc': 'Projeto pessoal onde recriei a interface da ElevenLabs utilizando Next.js, React, TypeScript e Styled-Components. Foco em replicar o design, animações e experiência visual completa da plataforma.',
    'project.portfolio.desc': 'Primeiro portfólio pessoal, desenvolvido em 1 mês com responsividade e várias animações. Site com 3 páginas mostrando perfil, projetos, cursos e certificações — basicamente um currículo interativo e mais abrangente.',
    'project.paragrafeado.desc': 'Projeto de navegação em React focado em componentização e roteamento. Interface limpa para exploração de conteúdo com navegação fluida entre páginas.',
    'project.netflix.desc': 'Releitura da Netflix com integração a banco de dados MySQL. Implementação de operações CRUD completas, conexão via PHP e diversas funcionalidades de gerenciamento de conteúdo. Projeto associado à Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Calculadora avançada desenvolvida em linguagem C com mais de 2.500 linhas de código. Projeto colaborativo realizado na Fatec Mogi das Cruzes, cobrindo desde operações básicas até funções matemáticas complexas.',
    'exp.title': 'Experiência',
    'exp.subtitle': 'Stacks & Vivência Profissional',
    'exp.p1': 'Arquitetei e desenvolvi (Front e Back) plataformas SaaS B2B Multi-tenant voltadas para o setor automotivo, conectando concessionárias, lojistas e prestadores de serviço. Implementei lógicas complexas de RBAC, gestão de garagens, leilões, planos de assinatura e integração de pagamentos com Pagar.me.',
    'exp.p2': 'Construí dashboards Admin e B2B complexos para e-commerce, redes sociais e ferramentas internas. Criei sistemas de chat em tempo real com Firebase e WebSockets, além de entregar projetos front-end como freelancer internacional via Upwork para clientes nos EUA.',
    'exp.stats.corporate': 'Projetos Corporativos',
    'exp.stats.fullstack': 'Projeto Corporativo (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certificações',
    'exp.stacks.label': 'Stacks Principais',
    'courses.title': 'Cursos',
    'courses.subtitle': 'Certificações & Aprendizado',
    'courses.count.single': 'curso encontrado',
    'courses.count.plural': 'cursos encontrados',
    'courses.filter.all': 'Todos',
    'courses.filter.organization': 'Organização',
    'courses.filter.skills': 'Competências',
    'courses.hours': 'horas',
    'month.1': 'Janeiro',
    'month.2': 'Fevereiro',
    'month.3': 'Março',
    'month.4': 'Abril',
    'month.5': 'Maio',
    'month.6': 'Junho',
    'month.7': 'Julho',
    'month.8': 'Agosto',
    'month.9': 'Setembro',
    'month.10': 'Outubro',
    'month.11': 'Novembro',
    'month.12': 'Dezembro',
    'date.preposition': ' de ',
    'changelog.title': 'Versões',
    'changelog.description': 'Histórico completo de atualizações e melhorias do portfolio.',
    'changelog.current': 'atual',
    'settings.page.title': 'Configurações',
    'settings.page.subtitle': 'Personalize sua experiência no portfolio.',
    'settings.page.tag': 'Preferências & Sistema',
    'settings.about.title': 'Sobre mim',
    'settings.about.bio': 'Desenvolvedor Full Stack apaixonado por criar experiências digitais modernas e fluidas.',
    'settings.theme.desc': 'Alterne entre os modos claro e escuro.',
    'settings.versions.title': 'Histórico de Versões',
    'settings.wip.section': 'Página Alternativa',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Visualize a versão inicial do portfolio, em construção.',
    'nav.settings': 'Configurações',
    'who.title': 'Quem sou eu?',
    'who.subtitle': 'Desenvolvedor Full Stack',
    'who.bio.p1': 'Tenho 22 anos e sempre fui apaixonado por design, especialmente voltado para a web. No começo, estudei bastante WordPress e Elementor, e hoje essa paixão só cresceu. Também sou muito ligado no inglês — escuto muitas músicas em inglês, tanto para melhorar meu nível quanto por puro gosto. Acredito que aprender nunca para, e isso me move todos os dias.',
    'who.bio.p2': 'Minhas soft skills incluem aprendizado rápido, comunicação clara, ótima organização e gosto por trabalhar sob pressão. Gosto de fazer parte de projetos importantes e sou prático na hora de resolver bugs, erros e problemas — prefiro resolver rápido e seguir em frente. Já conduzi reuniões com clientes, explicando o desenvolvimento e liderando a conversa. Gosto de trabalhar em equipe — embora às vezes me sinta mais produtivo focando sozinho em alguma atualização específica. Também gosto de liderar, ensinar e compartilhar conhecimento, sempre com respeito e colaboração.',
    'who.bio.p3': 'No dia a dia, gosto de tomar um café enquanto codo, sou fã de gatos, curto jogar de vez em quando e treinar na academia. Amo parar tudo para aprender algo novo — uma stack diferente, uma ferramenta, uma abordagem. Essa curiosidade constante é o que me mantém evoluindo como desenvolvedor.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Tecnologias & Vivência Profissional',
    'nav.skills': 'Habilidades',
    'skills.page.tag': 'Competências Técnicas',
    'skills.page.title': 'Skills',
    'skills.page.subtitle': 'As tecnologias e ferramentas que domino no dia a dia como desenvolvedor.',
    'skills.page.hint': 'Quanto maior o bloco, maior o domínio sobre a tecnologia.',
    'skills.frontend': 'Front-End',
    'skills.backend': 'Back-End & Banco de Dados',
    'skills.devops': 'DevOps & Ferramentas',
    'nav.timeline': 'Jornada',
    'timeline.page.tag': 'Histórico Profissional',
    'timeline.page.title': 'Minha Jornada',
    'timeline.page.subtitle': 'Uma linha do tempo com os principais marcos da minha carreira como desenvolvedor.',
    'timeline.cat.education': 'Educação',
    'timeline.cat.work': 'Trabalho',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Marco',
    'timeline.2026.projects': 'Participação em +16 Projetos na Empresa',
    'timeline.2026.projects.desc': 'Atuei em mais de 16 projetos corporativos na empresa, abrangendo plataformas B2B, B2C, dashboards, e-commerces e ferramentas internas.',
    'timeline.2026.fullstack': 'Estudando Estrutura SaaS & Full Stack',
    'timeline.2026.fullstack.desc': 'Primeiros projetos como Full Stack, estudando estrutura SaaS, Strapi, SSH, GitHub e Prisma. Aprofundamento em arquitetura e deploy.',
    'timeline.2026.english': 'Estudando Inglês por Conta Própria',
    'timeline.2026.english.desc': 'Continuando os estudos de inglês de forma autodidata. Nível atual: B2.',
    'timeline.2025.stack': 'Estudando Integrações Pesadas & Backend',
    'timeline.2025.stack.desc': 'Mergulho profundo em JSX, Node.js, integrações pesadas, backend, Pagar.me, Firebase, chat ao vivo, WebSockets, SaaS e muito mais.',
    'timeline.2025.hired': 'Contratado como Front-End Junior',
    'timeline.2025.hired.desc': 'Em 1 de outubro, fui efetivado como desenvolvedor Front-End Junior na empresa após período de estágio.',
    'timeline.2025.freela': 'Mais Um Projeto Freela Finalizado',
    'timeline.2025.freela.desc': 'Finalizei mais um projeto como freelancer, consolidando experiência em entregas internacionais.',
    'timeline.2025.english': 'Estudando Inglês por Conta Própria',
    'timeline.2025.english.desc': 'Estudos autodidatas de inglês. Nível atual: B2.',
    'timeline.2024.intern': 'Início como Estagiário Front-End',
    'timeline.2024.intern.desc': 'Em 14 de outubro, comecei a trabalhar na Mestres da Web como estagiário Front-End. Primeiro contato com ambiente corporativo real.',
    'timeline.2024.stack': 'Estudando JS, TS, React, Next & Mais',
    'timeline.2024.stack.desc': 'Estudando JavaScript, TypeScript, React, Next.js, API REST, Figma, Postman, Asana e Git. Evolução técnica acelerada.',
    'timeline.2024.freela': 'Primeiro Projeto Freela Finalizado',
    'timeline.2024.freela.desc': 'Primeiro projeto de freelance finalizado via Upwork. Entrega completa para cliente internacional.',
    'timeline.2024.courses': 'Cursos Finalizados',
    'timeline.2024.courses.desc': 'Finalizei diversos cursos e certificações, consolidando a base técnica.',
    'timeline.2024.english': 'Saí do Curso de Inglês',
    'timeline.2024.english.desc': 'Encerrei o curso formal de inglês. Nível alcançado: B1.',
    'timeline.2023.fatec': 'Início na FATEC MC — ADS',
    'timeline.2023.fatec.desc': 'Ingressei no curso de Análise e Desenvolvimento de Sistemas na FATEC Mogi das Cruzes.',
    'timeline.2023.courses': 'Cursos Finalizados',
    'timeline.2023.courses.desc': 'Finalizei cursos de desenvolvimento web e front-end.',
    'timeline.2023.frameworks': 'Estudando Bootstrap, jQuery, React & JS',
    'timeline.2023.frameworks.desc': 'Aprofundamento em frameworks e bibliotecas: Bootstrap, jQuery, React e JavaScript avançado.',
    'timeline.2023.english': 'Estudando Inglês por Conta Própria',
    'timeline.2023.english.desc': 'Estudos autodidatas de inglês. Nível atual: A2.',
    'timeline.2022.code': 'Primeiras Linhas de Código',
    'timeline.2022.code.desc': 'Escrevi minhas primeiras linhas de código em HTML, CSS e JavaScript. O início de tudo.',
    'timeline.2022.danki': 'Curso Danki Code Adquirido',
    'timeline.2022.danki.desc': 'Adquiri o curso Danki Code: Front-End Completo, Desenvolvimento Web Completo e Web Design Express.',
    'timeline.2022.english': 'Início no Curso de Inglês — Cultura Inglesa',
    'timeline.2022.english.desc': 'Comecei o curso de inglês no Cultura Inglesa. Nível inicial: A1.',
    'timeline.2021.sold': 'Primeiro Projeto Vendido',
    'timeline.2021.sold.desc': 'Meu primeiro projeto vendido usando WordPress com Elementor, hospedado na HostGator.',
    'timeline.2021.shopify': 'Estudando Shopify',
    'timeline.2021.shopify.desc': 'Estudando a plataforma Shopify para criação de e-commerces.',
    'timeline.2020.wordpress': 'Estudando WordPress (Elementor)',
    'timeline.2020.wordpress.desc': 'Primeiros passos no mundo do desenvolvimento web, aprendendo WordPress com Elementor.',
    'timeline.2020.hosting': 'Estudando Hospedagens (SSH, Domínios)',
    'timeline.2020.hosting.desc': 'Aprendendo sobre hospedagens, SSH, domínios e infraestrutura web.',
    'timeline.2020.webdesign': 'Estudando Web Design (Conceitos)',
    'timeline.2020.webdesign.desc': 'Estudando conceitos de web design, layout, cores e tipografia.',
    'github.viewProfile': 'Ver Perfil',
    'github.totalCommits': 'Commits Totais',
    'github.lastYear': 'Último Ano',
    'github.activeYears': 'Anos Ativos',
    'github.contributions': 'Contribuições',
    'github.inLastYear': 'no último ano',
    'github.contributionsLabel': 'contribuições',
    'github.less': 'Menos',
    'github.more': 'Mais',
    'nav.aboutme': 'Sobre Mim',
    'nav.cases': 'Cases',
    'nav.testimonials': 'Depoimentos',
    'cases.page.tag': 'Estudos de Caso',
    'cases.page.title': 'Cases',
    'cases.page.subtitle': 'Problemas reais que enfrentei e como os resolvi. Cada case mostra o raciocínio técnico por trás das entregas.',
    'cases.section.problem': 'O Problema',
    'cases.section.approach': 'A Abordagem',
    'cases.section.result': 'O Resultado',
    'cases.saas.title': 'Plataformas SaaS Multi-tenant B2B',
    'cases.saas.problem': 'O cliente precisava de uma plataforma que conectasse concessionárias, lojistas e prestadores de serviço no setor automotivo. A arquitetura deveria suportar múltiplos tenants com isolamento de dados, permissões complexas e fluxos de pagamento integrados.',
    'cases.saas.approach': 'Arquitetei uma solução Multi-tenant com RBAC granular usando Next.js no front e Node.js + Prisma no back. Implementei gestão de garagens, sistema de leilões, planos de assinatura e integração de pagamentos com Pagar.me. Cada tenant possui seu próprio escopo de dados com middleware de isolamento.',
    'cases.saas.result': 'Plataforma entregue e operando em produção com múltiplos clientes simultâneos. O sistema de RBAC permite controle fino de permissões por papel, e a integração com Pagar.me automatizou 100% do fluxo financeiro.',
    'cases.saas.metric1.label': 'Projetos Corporativos',
    'cases.saas.metric2.label': 'Controle de Acesso',
    'cases.saas.metric3.label': 'Arquitetura',
    'cases.chat.title': 'Sistema de Chat em Tempo Real',
    'cases.chat.problem': 'Um dos projetos corporativos exigia comunicação em tempo real entre usuários da plataforma. A solução precisava ser performática, escalável e manter o histórico de mensagens de forma confiável.',
    'cases.chat.approach': 'Implementei um sistema de chat usando Firebase Realtime Database para persistência e WebSockets para entrega instantânea. Criei hooks customizados para gerenciar conexões, presença online e notificações push. O front foi construído com React e TypeScript.',
    'cases.chat.result': 'Chat em produção com latência abaixo de 100ms. O sistema suporta conversas individuais e em grupo, com indicadores de presença e histórico completo persistido.',
    'cases.chat.metric1.label': 'Entrega',
    'cases.chat.metric2.label': 'Protocolo',
    'cases.chat.metric3.label': 'Latência',
    'cases.dashboard.title': 'Dashboards Admin & B2B Complexos',
    'cases.dashboard.problem': 'Múltiplos projetos da empresa exigiam dashboards administrativos complexos para e-commerce, redes sociais e ferramentas internas. Cada um com regras de negócio únicas, integrações pesadas e interfaces que precisavam ser pixel-perfect com o design do Figma.',
    'cases.dashboard.approach': 'Desenvolvi um sistema de componentes reutilizáveis em React + TypeScript + Styled-Components que acelerou a entrega de novos dashboards. Criei padrões de integração com APIs REST, gerenciamento de estado e tabelas dinâmicas com filtros avançados.',
    'cases.dashboard.result': 'Entreguei mais de 5 dashboards de alta complexidade. O design system criado reduziu o tempo de desenvolvimento em novos projetos e garantiu consistência visual em todos os produtos.',
    'cases.dashboard.metric1.label': 'Dashboards Entregues',
    'cases.dashboard.metric2.label': 'Segmentos',
    'cases.dashboard.metric3.label': 'Conversão',
    'cases.freelance.title': 'Freelance Internacional via Upwork',
    'cases.freelance.problem': 'Clientes nos EUA precisavam de um desenvolvedor front-end confiável para entregar projetos com prazos apertados, comunicação em inglês e qualidade de código compatível com equipes internacionais.',
    'cases.freelance.approach': 'Atuei como freelancer via Upwork, conduzindo reuniões em inglês, entendendo requisitos diretamente com os stakeholders e entregando projetos completos com Next.js, TypeScript e deploy na Vercel. Mantive comunicação assíncrona eficiente com fusos diferentes.',
    'cases.freelance.result': 'Todos os projetos entregues no prazo com avaliação máxima. A experiência internacional solidificou minhas habilidades de comunicação em inglês e gestão de projetos remotos.',
    'cases.freelance.metric1.label': 'Clientes',
    'cases.freelance.metric2.label': 'Plataforma',
    'cases.freelance.metric3.label': 'Satisfação',
    'testimonials.page.tag': 'Depoimentos',
    'testimonials.page.title': 'O que dizem sobre mim',
    'testimonials.page.subtitle': 'Feedback de gestores, colegas e clientes com quem tive o prazer de trabalhar.',
    'testimonials.manager.quote': 'Arthur demonstra uma capacidade técnica excepcional e uma proatividade impressionante. Ele liderou implementações complexas com autonomia, sempre entregando com qualidade e dentro do prazo.',
    'testimonials.client.quote': 'Excellent developer. Arthur understood our requirements quickly and delivered a polished product. His communication was clear and professional throughout the project.',
    'testimonials.colleague.quote': 'Trabalhar com o Arthur é muito produtivo. Ele tem uma visão técnica forte, ajuda o time a resolver bugs rapidamente e sempre compartilha conhecimento de forma colaborativa.'
  },
  en: {
    'hero.greeting': 'Hi, I am',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Building modern, fluid digital experiences focused on product excellence, from elegant design to robust architecture.',
    'hero.btn.primary': 'Continue',
    'hero.btn.secondary': 'Get in Touch',
    'about.title': 'About me',
    'about.subtitle': 'Software Engineer & Full Stack',
    'about.p1':
      'Software Developer with strong specialization in Front-End (React.js, Next.js, TypeScript) and solid experience in Back-End architecture (Node.js, Prisma) for building complete SaaS products.',
    'about.p2':
      'I have experience transforming Figma designs into fast and scalable web applications, uniting clean code with complex business rules. Currently pursuing a degree in Systems Analysis and Development at FATEC.',
    'about.p3':
      'I have worked on more than 15 corporate projects and as an international freelancer. I bridge the gap between UI/UX design and technical solutions, working closely with Product Owners and QAs in Agile teams, leading end-to-end technical development.',
    'about.stats.projects': 'B2B & B2C Projects',
    'about.stats.years': 'Years Exp',
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'Moments & Behind the Scenes',
    'nav.home': 'Home',
    'nav.about': 'About me',
    'nav.projects': 'Projects',
    'nav.portfolio': 'Portfolio',
    'nav.courses': 'Courses',
    'nav.cta': 'Contact',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light Mode',
    'settings.theme.dark': 'Dark Mode',
    'settings.theme.light.short': 'Light',
    'settings.theme.dark.short': 'Dark',
    'settings.language': 'Language',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.copyright': 'All rights reserved.',
    'footer.changelog.viewAll': 'View all versions →',
    'footer.bio': 'Software Engineer & Full Stack — building modern digital products, from design to architecture. Focused on React, Next.js and TypeScript.',
    'footer.versions': 'Versions',
    'projects.personal': 'Personal',
    'projects.company': 'Company',
    'projects.university': 'University',
    'projects.personal.desc': 'Projects & Experiments',
    'projects.company.desc': 'Professional Work',
    'projects.university.desc': 'Academic Work',
    'projects.title.personal': 'Personal Projects',
    'projects.title.company': 'Company Projects',
    'projects.title.university': 'University Projects',
    'projects.subtitle.personal': 'Projects & Experiments',
    'projects.subtitle.company': 'Professional Work',
    'projects.subtitle.university': 'Academic Work',
    'projects.empty': 'No projects added yet. Coming soon!',
    'project.elevenlabs.desc': 'Personal project where I recreated the ElevenLabs interface using Next.js, React, TypeScript and Styled-Components. Focused on replicating the design, animations and overall visual experience of the platform.',
    'project.portfolio.desc': 'First personal portfolio, built in 1 month with responsiveness and multiple animations. A 3-page site showcasing profile, projects, courses and certifications — essentially an interactive and comprehensive résumé.',
    'project.paragrafeado.desc': 'React navigation project focused on componentization and routing. Clean interface for content exploration with fluid page navigation.',
    'project.netflix.desc': 'Netflix redesign with MySQL database integration. Full CRUD operations, PHP connection and various content management features. Project associated with Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Advanced calculator built in C with over 2,500 lines of code. Collaborative project at Fatec Mogi das Cruzes, covering basic operations to complex mathematical functions.',
    'exp.title': 'Experience',
    'exp.subtitle': 'Stacks & Professional Background',
    'exp.p1': 'I architected and developed (Front and Back) B2B Multi-tenant SaaS platforms for the automotive sector, connecting dealerships, retailers and service providers. I implemented complex RBAC logic, garage management, auctions, subscription plans and payment integration with Pagar.me.',
    'exp.p2': 'I built complex Admin and B2B dashboards for e-commerce, social networks and internal tools. I created real-time chat systems using Firebase and WebSockets, and delivered front-end projects as an international freelancer via Upwork for US-based clients.',
    'exp.stats.corporate': 'Corporate Projects',
    'exp.stats.fullstack': 'Corporate Project (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certifications',
    'exp.stacks.label': 'Main Stacks',
    'courses.title': 'Courses',
    'courses.subtitle': 'Certifications & Learning',
    'courses.count.single': 'course found',
    'courses.count.plural': 'courses found',
    'courses.filter.all': 'All',
    'courses.filter.organization': 'Organization',
    'courses.filter.skills': 'Skills',
    'courses.hours': 'hours',
    'month.1': 'January',
    'month.2': 'February',
    'month.3': 'March',
    'month.4': 'April',
    'month.5': 'May',
    'month.6': 'June',
    'month.7': 'July',
    'month.8': 'August',
    'month.9': 'September',
    'month.10': 'October',
    'month.11': 'November',
    'month.12': 'December',
    'date.preposition': ' ',
    'changelog.title': 'Versions',
    'changelog.description': 'Complete update and improvement history of the portfolio.',
    'changelog.current': 'current',
    'settings.page.title': 'Settings',
    'settings.page.subtitle': 'Customize your portfolio experience.',
    'settings.page.tag': 'Preferences & System',
    'settings.about.title': 'About me',
    'settings.about.bio': 'Full Stack developer passionate about building modern and fluid digital experiences.',
    'settings.theme.desc': 'Switch between light and dark modes.',
    'settings.versions.title': 'Version History',
    'settings.wip.section': 'Alternative Page',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'View the initial version of the portfolio, under construction.',
    'nav.settings': 'Settings',
    'who.title': 'Who am I?',
    'who.subtitle': 'Full Stack Developer',
    'who.bio.p1': 'I\'m 22 years old and I\'ve always been passionate about design, especially for the web. Early on, I studied WordPress and Elementor extensively, and today that passion has only grown stronger. I\'m also really into English — I listen to a lot of English music, both to improve my skills and simply because I enjoy it. I believe learning never stops, and that mindset drives me every day.',
    'who.bio.p2': 'My soft skills include fast learning, clear communication, strong organization, and a taste for working under pressure. I enjoy being part of important projects and I\'m very hands-on when it comes to fixing bugs, errors, and problems — I prefer to resolve things quickly and move forward. I\'ve led meetings with clients, explaining the development process and driving the conversation. I enjoy teamwork — though sometimes I feel more productive focusing solo on a specific update. I also like to lead, teach, and share knowledge, always with respect and collaboration.',
    'who.bio.p3': 'On a daily basis, I enjoy drinking coffee while coding, I\'m a cat lover, I like gaming from time to time, and hitting the gym. I love stopping everything to learn something new — a different stack, a tool, a new approach. This constant curiosity is what keeps me evolving as a developer.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Technologies & Professional Background',
    'nav.skills': 'Skills',
    'skills.page.tag': 'Technical Skills',
    'skills.page.title': 'Skills',
    'skills.page.subtitle': 'The technologies and tools I use daily as a developer.',
    'skills.page.hint': 'The larger the block, the greater the mastery of the technology.',
    'skills.frontend': 'Front-End',
    'skills.backend': 'Back-End & Databases',
    'skills.devops': 'DevOps & Tools',
    'nav.timeline': 'Journey',
    'timeline.page.tag': 'Professional History',
    'timeline.page.title': 'My Journey',
    'timeline.page.subtitle': 'A timeline of the main milestones in my career as a developer.',
    'timeline.cat.education': 'Education',
    'timeline.cat.work': 'Work',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Milestone',
    'timeline.2026.projects': 'Participation in 16+ Company Projects',
    'timeline.2026.projects.desc': 'Worked on over 16 corporate projects including B2B, B2C platforms, dashboards, e-commerces and internal tools.',
    'timeline.2026.fullstack': 'Studying SaaS Structure & Full Stack',
    'timeline.2026.fullstack.desc': 'First projects as Full Stack, studying SaaS structure, Strapi, SSH, GitHub and Prisma. Deepening architecture and deployment skills.',
    'timeline.2026.english': 'Self-studying English',
    'timeline.2026.english.desc': 'Continuing English studies on my own. Current level: B2.',
    'timeline.2025.stack': 'Studying Heavy Integrations & Backend',
    'timeline.2025.stack.desc': 'Deep dive into JSX, Node.js, heavy integrations, backend, Pagar.me, Firebase, live chat, WebSockets, SaaS and much more.',
    'timeline.2025.hired': 'Hired as Front-End Junior',
    'timeline.2025.hired.desc': 'On October 1st, I was hired as a Front-End Junior developer after the internship period.',
    'timeline.2025.freela': 'Another Freelance Project Completed',
    'timeline.2025.freela.desc': 'Completed another freelance project, consolidating experience in international deliveries.',
    'timeline.2025.english': 'Self-studying English',
    'timeline.2025.english.desc': 'Self-taught English studies. Current level: B2.',
    'timeline.2024.intern': 'Started as Front-End Intern',
    'timeline.2024.intern.desc': 'On October 14th, I started working at Mestres da Web as a Front-End intern. First real corporate environment experience.',
    'timeline.2024.stack': 'Studying JS, TS, React, Next & More',
    'timeline.2024.stack.desc': 'Studying JavaScript, TypeScript, React, Next.js, REST API, Figma, Postman, Asana and Git. Accelerated technical growth.',
    'timeline.2024.freela': 'First Freelance Project Completed',
    'timeline.2024.freela.desc': 'First freelance project completed via Upwork. Full delivery for an international client.',
    'timeline.2024.courses': 'Courses Completed',
    'timeline.2024.courses.desc': 'Completed several courses and certifications, solidifying the technical foundation.',
    'timeline.2024.english': 'Left English Course',
    'timeline.2024.english.desc': 'Left the formal English course. Level reached: B1.',
    'timeline.2023.fatec': 'Started at FATEC MC — ADS',
    'timeline.2023.fatec.desc': 'Enrolled in Systems Analysis and Development at FATEC Mogi das Cruzes.',
    'timeline.2023.courses': 'Courses Completed',
    'timeline.2023.courses.desc': 'Completed web development and front-end courses.',
    'timeline.2023.frameworks': 'Studying Bootstrap, jQuery, React & JS',
    'timeline.2023.frameworks.desc': 'Deep dive into frameworks and libraries: Bootstrap, jQuery, React and advanced JavaScript.',
    'timeline.2023.english': 'Self-studying English',
    'timeline.2023.english.desc': 'Self-taught English studies. Current level: A2.',
    'timeline.2022.code': 'First Lines of Code',
    'timeline.2022.code.desc': 'Wrote my first lines of code in HTML, CSS and JavaScript. The beginning of everything.',
    'timeline.2022.danki': 'Danki Code Course Acquired',
    'timeline.2022.danki.desc': 'Acquired the Danki Code course: Complete Front-End, Complete Web Development and Web Design Express.',
    'timeline.2022.english': 'Started English Course — Cultura Inglesa',
    'timeline.2022.english.desc': 'Started English course at Cultura Inglesa. Starting level: A1.',
    'timeline.2021.sold': 'First Project Sold',
    'timeline.2021.sold.desc': 'My first project sold using WordPress with Elementor, hosted on HostGator.',
    'timeline.2021.shopify': 'Studying Shopify',
    'timeline.2021.shopify.desc': 'Studying the Shopify platform for e-commerce creation.',
    'timeline.2020.wordpress': 'Studying WordPress (Elementor)',
    'timeline.2020.wordpress.desc': 'First steps into web development, learning WordPress with Elementor.',
    'timeline.2020.hosting': 'Studying Hosting (SSH, Domains)',
    'timeline.2020.hosting.desc': 'Learning about hosting, SSH, domains and web infrastructure.',
    'timeline.2020.webdesign': 'Studying Web Design (Concepts)',
    'timeline.2020.webdesign.desc': 'Studying web design concepts, layout, colors and typography.',
    'github.viewProfile': 'View Profile',
    'github.totalCommits': 'Total Commits',
    'github.lastYear': 'Last Year',
    'github.activeYears': 'Active Years',
    'github.contributions': 'Contributions',
    'github.inLastYear': 'in the last year',
    'github.contributionsLabel': 'contributions',
    'github.less': 'Less',
    'github.more': 'More',
    'nav.aboutme': 'About Me',
    'nav.cases': 'Case Studies',
    'nav.testimonials': 'Testimonials',
    'cases.page.tag': 'Case Studies',
    'cases.page.title': 'Cases',
    'cases.page.subtitle': 'Real problems I faced and how I solved them. Each case shows the technical reasoning behind the deliveries.',
    'cases.section.problem': 'The Problem',
    'cases.section.approach': 'The Approach',
    'cases.section.result': 'The Result',
    'cases.saas.title': 'Multi-tenant B2B SaaS Platforms',
    'cases.saas.problem': 'The client needed a platform connecting dealerships, retailers and service providers in the automotive sector. The architecture had to support multiple tenants with data isolation, complex permissions and integrated payment flows.',
    'cases.saas.approach': 'I architected a Multi-tenant solution with granular RBAC using Next.js on the front and Node.js + Prisma on the back. I implemented garage management, auction systems, subscription plans and payment integration with Pagar.me. Each tenant has its own data scope with isolation middleware.',
    'cases.saas.result': 'Platform delivered and running in production with multiple simultaneous clients. The RBAC system allows fine-grained permission control by role, and the Pagar.me integration automated 100% of the financial flow.',
    'cases.saas.metric1.label': 'Corporate Projects',
    'cases.saas.metric2.label': 'Access Control',
    'cases.saas.metric3.label': 'Architecture',
    'cases.chat.title': 'Real-Time Chat System',
    'cases.chat.problem': 'One of the corporate projects required real-time communication between platform users. The solution needed to be performant, scalable and reliably maintain message history.',
    'cases.chat.approach': 'I implemented a chat system using Firebase Realtime Database for persistence and WebSockets for instant delivery. I created custom hooks to manage connections, online presence and push notifications. The front was built with React and TypeScript.',
    'cases.chat.result': 'Chat in production with latency below 100ms. The system supports individual and group conversations, with presence indicators and fully persisted history.',
    'cases.chat.metric1.label': 'Delivery',
    'cases.chat.metric2.label': 'Protocol',
    'cases.chat.metric3.label': 'Latency',
    'cases.dashboard.title': 'Complex Admin & B2B Dashboards',
    'cases.dashboard.problem': 'Multiple company projects required complex admin dashboards for e-commerce, social networks and internal tools. Each with unique business rules, heavy integrations and pixel-perfect Figma interfaces.',
    'cases.dashboard.approach': 'I developed a reusable component system in React + TypeScript + Styled-Components that accelerated new dashboard delivery. I created REST API integration patterns, state management and dynamic tables with advanced filters.',
    'cases.dashboard.result': 'Delivered over 5 high-complexity dashboards. The design system reduced development time on new projects and ensured visual consistency across all products.',
    'cases.dashboard.metric1.label': 'Dashboards Delivered',
    'cases.dashboard.metric2.label': 'Segments',
    'cases.dashboard.metric3.label': 'Conversion',
    'cases.freelance.title': 'International Freelance via Upwork',
    'cases.freelance.problem': 'US clients needed a reliable front-end developer to deliver projects with tight deadlines, English communication and code quality compatible with international teams.',
    'cases.freelance.approach': 'I worked as a freelancer via Upwork, leading meetings in English, understanding requirements directly with stakeholders and delivering complete projects with Next.js, TypeScript and Vercel deployment. I maintained efficient async communication across time zones.',
    'cases.freelance.result': 'All projects delivered on time with top ratings. The international experience solidified my English communication skills and remote project management.',
    'cases.freelance.metric1.label': 'Clients',
    'cases.freelance.metric2.label': 'Platform',
    'cases.freelance.metric3.label': 'Satisfaction',
    'testimonials.page.tag': 'Testimonials',
    'testimonials.page.title': 'What they say about me',
    'testimonials.page.subtitle': 'Feedback from managers, colleagues and clients I had the pleasure of working with.',
    'testimonials.manager.quote': 'Arthur demonstrates exceptional technical ability and impressive proactivity. He led complex implementations autonomously, always delivering with quality and on time.',
    'testimonials.client.quote': 'Excellent developer. Arthur understood our requirements quickly and delivered a polished product. His communication was clear and professional throughout the project.',
    'testimonials.colleague.quote': 'Working with Arthur is very productive. He has a strong technical vision, helps the team fix bugs quickly and always shares knowledge collaboratively.'
  },
  fr: {
    'hero.greeting': 'Bonjour, je suis',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Création d\'expériences numériques modernes, fluides et axées sur l\'excellence produit, du design élégant à l\'architecture robuste.',
    'hero.btn.primary': 'Continuer',
    'hero.btn.secondary': 'Me Contacter',
    'about.title': 'À propos',
    'about.subtitle': 'Ingénieur Logiciel & Full Stack',
    'about.p1':
      'Développeur logiciel avec une forte spécialisation en Front-End (React.js, Next.js, TypeScript) et une expérience solide en architecture Back-End (Node.js, Prisma) pour la construction de produits SaaS complets.',
    'about.p2':
      'J\'ai de l\'expérience dans la transformation de designs Figma en applications web rapides et évolutives, alliant code propre et règles métier complexes. Actuellement en formation en Analyse et Développement de Systèmes à la FATEC.',
    'about.p3':
      'J\'ai travaillé sur plus de 15 projets d\'entreprise et en tant que freelance international. Je fais le pont entre le design UI/UX et les solutions techniques, en collaboration directe avec les Product Owners et QAs dans des équipes Agiles, pilotant le développement technique de bout en bout.',
    'about.stats.projects': 'Projets B2B & B2C',
    'about.stats.years': 'Ans d\'Exp',
    'gallery.title': 'Galerie',
    'gallery.subtitle': 'Moments & Coulisses',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.projects': 'Projets',
    'nav.portfolio': 'Portfolio',
    'nav.courses': 'Formations',
    'nav.cta': 'Contact',
    'settings.theme': 'Thème',
    'settings.theme.light': 'Mode Clair',
    'settings.theme.dark': 'Mode Sombre',
    'settings.theme.light.short': 'Clair',
    'settings.theme.dark.short': 'Sombre',
    'settings.language': 'Langue',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.copyright': 'Tous droits réservés.',
    'footer.changelog.viewAll': 'Voir toutes les versions →',
    'footer.bio': 'Software Engineer & Full Stack — création de produits numériques modernes, du design à l\'architecture. Spécialisé en React, Next.js et TypeScript.',
    'footer.versions': 'Versions',
    'projects.personal': 'Personnels',
    'projects.company': 'Entreprise',
    'projects.university': 'Université',
    'projects.personal.desc': 'Projets & Expériences',
    'projects.company.desc': 'Travail Professionnel',
    'projects.university.desc': 'Travail Académique',
    'projects.title.personal': 'Projets Personnels',
    'projects.title.company': 'Projets d\'Entreprise',
    'projects.title.university': 'Projets Universitaires',
    'projects.subtitle.personal': 'Projets & Expériences',
    'projects.subtitle.company': 'Travail Professionnel',
    'projects.subtitle.university': 'Travail Académique',
    'projects.empty': 'Aucun projet ajouté pour le moment. Bientôt disponible !',
    'project.elevenlabs.desc': 'Projet personnel où j\'ai recréé l\'interface ElevenLabs avec Next.js, React, TypeScript et Styled-Components. Axé sur la reproduction du design, des animations et de l\'expérience visuelle de la plateforme.',
    'project.portfolio.desc': 'Premier portfolio personnel, développé en 1 mois avec responsivité et animations multiples. Un site de 3 pages présentant profil, projets, formations et certifications — un CV interactif et complet.',
    'project.paragrafeado.desc': 'Projet de navigation React axé sur la composantisation et le routage. Interface épurée pour l\'exploration de contenu avec navigation fluide entre les pages.',
    'project.netflix.desc': 'Refonte de Netflix avec intégration MySQL. Opérations CRUD complètes, connexion PHP et fonctionnalités de gestion de contenu. Projet associé à Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Calculatrice avancée développée en C avec plus de 2 500 lignes de code. Projet collaboratif à Fatec Mogi das Cruzes, couvrant des opérations basiques aux fonctions mathématiques complexes.',
    'exp.title': 'Expérience',
    'exp.subtitle': 'Stacks & Parcours Professionnel',
    'exp.p1': 'J\'ai conçu et développé (Front et Back) des plateformes SaaS B2B Multi-tenant pour le secteur automobile, connectant concessionnaires, détaillants et prestataires. J\'ai implémenté des logiques RBAC complexes, gestion de garages, enchères, abonnements et intégration de paiements avec Pagar.me.',
    'exp.p2': 'J\'ai construit des dashboards Admin et B2B complexes pour l\'e-commerce, les réseaux sociaux et les outils internes. J\'ai créé des systèmes de chat en temps réel avec Firebase et WebSockets, et livré des projets front-end en tant que freelance international via Upwork pour des clients américains.',
    'exp.stats.corporate': 'Projets Entreprise',
    'exp.stats.fullstack': 'Projet Entreprise (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certifications',
    'exp.stacks.label': 'Stacks Principales',
    'courses.title': 'Formations',
    'courses.subtitle': 'Certifications & Apprentissage',
    'courses.count.single': 'formation trouvée',
    'courses.count.plural': 'formations trouvées',
    'courses.filter.all': 'Tous',
    'courses.filter.organization': 'Organisation',
    'courses.filter.skills': 'Compétences',
    'courses.hours': 'heures',
    'month.1': 'Janvier',
    'month.2': 'Février',
    'month.3': 'Mars',
    'month.4': 'Avril',
    'month.5': 'Mai',
    'month.6': 'Juin',
    'month.7': 'Juillet',
    'month.8': 'Août',
    'month.9': 'Septembre',
    'month.10': 'Octobre',
    'month.11': 'Novembre',
    'month.12': 'Décembre',
    'date.preposition': ' ',
    'changelog.title': 'Versions',
    'changelog.description': 'Historique complet des mises à jour et améliorations du portfolio.',
    'changelog.current': 'actuel',
    'settings.page.title': 'Paramètres',
    'settings.page.subtitle': 'Personnalisez votre expérience sur le portfolio.',
    'settings.page.tag': 'Préférences & Système',
    'settings.about.title': 'À propos',
    'settings.about.bio': 'Développeur Full Stack passionné par la création d\'expériences numériques modernes et fluides.',
    'settings.theme.desc': 'Basculez entre les modes clair et sombre.',
    'settings.versions.title': 'Historique des Versions',
    'settings.wip.section': 'Page Alternative',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Voir la version initiale du portfolio, en construction.',
    'nav.settings': 'Paramètres',
    'who.title': 'Qui suis-je ?',
    'who.subtitle': 'Développeur Full Stack',
    'who.bio.p1': 'J\'ai 22 ans et j\'ai toujours été passionné par le design, surtout pour le web. Au début, j\'ai beaucoup étudié WordPress et Elementor, et aujourd\'hui cette passion n\'a fait que grandir. Je suis aussi très branché anglais — j\'écoute beaucoup de musique en anglais, autant pour progresser que par pur plaisir. Je crois que l\'apprentissage ne s\'arrête jamais, et c\'est ce qui me motive chaque jour.',
    'who.bio.p2': 'Mes soft skills incluent un apprentissage rapide, une communication claire, une excellente organisation et le goût du travail sous pression. J\'aime faire partie de projets importants et je suis très pragmatique face aux bugs, erreurs et problèmes — je préfère résoudre vite et avancer. J\'ai déjà conduit des réunions avec des clients, expliquant le développement et menant la discussion. J\'aime travailler en équipe — même si parfois je me sens plus productif en me concentrant seul sur une mise à jour spécifique. J\'aime aussi diriger, enseigner et partager mes connaissances, toujours avec respect et collaboration.',
    'who.bio.p3': 'Au quotidien, j\'aime boire un café en codant, je suis fan de chats, j\'aime jouer de temps en temps et m\'entraîner à la salle. J\'adore tout arrêter pour apprendre quelque chose de nouveau — un nouveau stack, un outil, une approche différente. Cette curiosité constante est ce qui me fait évoluer en tant que développeur.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Technologies & Parcours Professionnel',
    'nav.skills': 'Compétences',
    'skills.page.tag': 'Compétences Techniques',
    'skills.page.title': 'Skills',
    'skills.page.subtitle': 'Les technologies et outils que j\'utilise au quotidien en tant que développeur.',
    'skills.page.hint': 'Plus le bloc est grand, plus la maîtrise de la technologie est élevée.',
    'skills.frontend': 'Front-End',
    'skills.backend': 'Back-End & Bases de Données',
    'skills.devops': 'DevOps & Outils',
    'nav.timeline': 'Parcours',
    'timeline.page.tag': 'Historique Professionnel',
    'timeline.page.title': 'Mon Parcours',
    'timeline.page.subtitle': 'Une chronologie des principaux jalons de ma carrière en tant que développeur.',
    'timeline.cat.education': 'Éducation',
    'timeline.cat.work': 'Travail',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Jalon',
    'timeline.2026.projects': 'Participation à +16 Projets en Entreprise',
    'timeline.2026.projects.desc': 'Travaillé sur plus de 16 projets d\'entreprise incluant plateformes B2B, B2C, tableaux de bord et outils internes.',
    'timeline.2026.fullstack': 'Études Structure SaaS & Full Stack',
    'timeline.2026.fullstack.desc': 'Premiers projets Full Stack, études SaaS, Strapi, SSH, GitHub et Prisma.',
    'timeline.2026.english': 'Auto-apprentissage de l\'Anglais',
    'timeline.2026.english.desc': 'Poursuite des études d\'anglais en autodidacte. Niveau actuel : B2.',
    'timeline.2025.stack': 'Études Intégrations Lourdes & Backend',
    'timeline.2025.stack.desc': 'Plongée dans JSX, Node.js, intégrations lourdes, backend, Pagar.me, Firebase, chat en direct, WebSockets, SaaS.',
    'timeline.2025.hired': 'Embauché comme Front-End Junior',
    'timeline.2025.hired.desc': 'Le 1er octobre, embauché comme développeur Front-End Junior après le stage.',
    'timeline.2025.freela': 'Un Autre Projet Freelance Terminé',
    'timeline.2025.freela.desc': 'Terminé un autre projet freelance, consolidant l\'expérience internationale.',
    'timeline.2025.english': 'Auto-apprentissage de l\'Anglais',
    'timeline.2025.english.desc': 'Études d\'anglais en autodidacte. Niveau actuel : B2.',
    'timeline.2024.intern': 'Début en tant que Stagiaire Front-End',
    'timeline.2024.intern.desc': 'Le 14 octobre, début chez Mestres da Web comme stagiaire Front-End.',
    'timeline.2024.stack': 'Études JS, TS, React, Next & Plus',
    'timeline.2024.stack.desc': 'JavaScript, TypeScript, React, Next.js, API REST, Figma, Postman, Asana et Git.',
    'timeline.2024.freela': 'Premier Projet Freelance Terminé',
    'timeline.2024.freela.desc': 'Premier projet freelance terminé via Upwork pour un client international.',
    'timeline.2024.courses': 'Formations Terminées',
    'timeline.2024.courses.desc': 'Terminé plusieurs formations et certifications.',
    'timeline.2024.english': 'Fin du Cours d\'Anglais',
    'timeline.2024.english.desc': 'Fin du cours formel d\'anglais. Niveau atteint : B1.',
    'timeline.2023.fatec': 'Début à la FATEC MC — ADS',
    'timeline.2023.fatec.desc': 'Inscription en Analyse et Développement de Systèmes à la FATEC Mogi das Cruzes.',
    'timeline.2023.courses': 'Formations Terminées',
    'timeline.2023.courses.desc': 'Terminé les formations en développement web et front-end.',
    'timeline.2023.frameworks': 'Études Bootstrap, jQuery, React & JS',
    'timeline.2023.frameworks.desc': 'Approfondissement des frameworks : Bootstrap, jQuery, React et JavaScript avancé.',
    'timeline.2023.english': 'Auto-apprentissage de l\'Anglais',
    'timeline.2023.english.desc': 'Études d\'anglais en autodidacte. Niveau actuel : A2.',
    'timeline.2022.code': 'Premières Lignes de Code',
    'timeline.2022.code.desc': 'Premières lignes de code en HTML, CSS et JavaScript. Le début de tout.',
    'timeline.2022.danki': 'Cours Danki Code Acquis',
    'timeline.2022.danki.desc': 'Acquisition du cours Danki Code : Front-End Complet, Développement Web Complet et Web Design Express.',
    'timeline.2022.english': 'Début Cours d\'Anglais — Cultura Inglesa',
    'timeline.2022.english.desc': 'Début du cours d\'anglais chez Cultura Inglesa. Niveau initial : A1.',
    'timeline.2021.sold': 'Premier Projet Vendu',
    'timeline.2021.sold.desc': 'Premier projet vendu avec WordPress et Elementor, hébergé sur HostGator.',
    'timeline.2021.shopify': 'Études Shopify',
    'timeline.2021.shopify.desc': 'Études de la plateforme Shopify pour la création d\'e-commerces.',
    'timeline.2020.wordpress': 'Études WordPress (Elementor)',
    'timeline.2020.wordpress.desc': 'Premiers pas dans le développement web, apprentissage de WordPress avec Elementor.',
    'timeline.2020.hosting': 'Études Hébergements (SSH, Domaines)',
    'timeline.2020.hosting.desc': 'Apprentissage des hébergements, SSH, domaines et infrastructure web.',
    'timeline.2020.webdesign': 'Études Web Design (Concepts)',
    'timeline.2020.webdesign.desc': 'Études des concepts de web design, mise en page, couleurs et typographie.',
    'github.viewProfile': 'Voir le Profil',
    'github.totalCommits': 'Commits Totaux',
    'github.lastYear': 'Dernière Année',
    'github.activeYears': 'Années Actives',
    'github.contributions': 'Contributions',
    'github.inLastYear': 'dans la dernière année',
    'github.contributionsLabel': 'contributions',
    'github.less': 'Moins',
    'github.more': 'Plus',
    'nav.aboutme': 'À propos',
    'nav.cases': 'Études de Cas',
    'nav.testimonials': 'Témoignages',
    'cases.page.tag': 'Études de Cas',
    'cases.page.title': 'Cases',
    'cases.page.subtitle': 'Problèmes réels que j\'ai rencontrés et comment je les ai résolus. Chaque cas montre le raisonnement technique derrière les livraisons.',
    'cases.section.problem': 'Le Problème',
    'cases.section.approach': 'L\'Approche',
    'cases.section.result': 'Le Résultat',
    'cases.saas.title': 'Plateformes SaaS Multi-tenant B2B',
    'cases.saas.problem': 'Le client avait besoin d\'une plateforme connectant concessionnaires, détaillants et prestataires dans le secteur automobile. L\'architecture devait supporter de multiples tenants avec isolation des données, permissions complexes et flux de paiement intégrés.',
    'cases.saas.approach': 'J\'ai conçu une solution Multi-tenant avec RBAC granulaire utilisant Next.js côté front et Node.js + Prisma côté back. J\'ai implémenté la gestion de garages, les enchères, les abonnements et l\'intégration des paiements avec Pagar.me.',
    'cases.saas.result': 'Plateforme livrée et opérationnelle en production avec plusieurs clients simultanés. Le système RBAC permet un contrôle fin des permissions par rôle.',
    'cases.saas.metric1.label': 'Projets Entreprise',
    'cases.saas.metric2.label': 'Contrôle d\'Accès',
    'cases.saas.metric3.label': 'Architecture',
    'cases.chat.title': 'Système de Chat en Temps Réel',
    'cases.chat.problem': 'Un des projets d\'entreprise nécessitait une communication en temps réel entre les utilisateurs. La solution devait être performante, évolutive et maintenir l\'historique de manière fiable.',
    'cases.chat.approach': 'J\'ai implémenté un système de chat utilisant Firebase Realtime Database et WebSockets. J\'ai créé des hooks personnalisés pour gérer les connexions, la présence en ligne et les notifications push.',
    'cases.chat.result': 'Chat en production avec une latence inférieure à 100ms. Le système supporte les conversations individuelles et de groupe.',
    'cases.chat.metric1.label': 'Livraison',
    'cases.chat.metric2.label': 'Protocole',
    'cases.chat.metric3.label': 'Latence',
    'cases.dashboard.title': 'Dashboards Admin & B2B Complexes',
    'cases.dashboard.problem': 'Plusieurs projets d\'entreprise nécessitaient des dashboards administratifs complexes pour l\'e-commerce, les réseaux sociaux et les outils internes.',
    'cases.dashboard.approach': 'J\'ai développé un système de composants réutilisables en React + TypeScript + Styled-Components qui a accéléré la livraison de nouveaux dashboards.',
    'cases.dashboard.result': 'Plus de 5 dashboards de haute complexité livrés. Le design system a réduit le temps de développement et assuré la cohérence visuelle.',
    'cases.dashboard.metric1.label': 'Dashboards Livrés',
    'cases.dashboard.metric2.label': 'Segments',
    'cases.dashboard.metric3.label': 'Conversion',
    'cases.freelance.title': 'Freelance International via Upwork',
    'cases.freelance.problem': 'Des clients aux États-Unis avaient besoin d\'un développeur front-end fiable pour livrer des projets dans des délais serrés avec communication en anglais.',
    'cases.freelance.approach': 'J\'ai travaillé comme freelance via Upwork, menant des réunions en anglais et livrant des projets complets avec Next.js, TypeScript et déploiement Vercel.',
    'cases.freelance.result': 'Tous les projets livrés dans les délais avec évaluation maximale. L\'expérience internationale a renforcé mes compétences en communication anglaise.',
    'cases.freelance.metric1.label': 'Clients',
    'cases.freelance.metric2.label': 'Plateforme',
    'cases.freelance.metric3.label': 'Satisfaction',
    'testimonials.page.tag': 'Témoignages',
    'testimonials.page.title': 'Ce qu\'ils disent de moi',
    'testimonials.page.subtitle': 'Retours de gestionnaires, collègues et clients avec qui j\'ai eu le plaisir de travailler.',
    'testimonials.manager.quote': 'Arthur démontre une capacité technique exceptionnelle et une proactivité impressionnante. Il a dirigé des implémentations complexes avec autonomie.',
    'testimonials.client.quote': 'Excellent developer. Arthur understood our requirements quickly and delivered a polished product. His communication was clear and professional throughout the project.',
    'testimonials.colleague.quote': 'Travailler avec Arthur est très productif. Il a une vision technique forte, aide l\'équipe à résoudre les bugs rapidement et partage toujours ses connaissances.'
  },
  ru: {
    'hero.greeting': 'Привет, я',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Создание современных, плавных цифровых решений с фокусом на качество продукта — от элегантного дизайна до надёжной архитектуры.',
    'hero.btn.primary': 'Продолжить',
    'hero.btn.secondary': 'Связаться',
    'about.title': 'Обо мне',
    'about.subtitle': 'Инженер-программист & Full Stack',
    'about.p1':
      'Разработчик ПО с сильной специализацией во Front-End (React.js, Next.js, TypeScript) и солидным опытом в архитектуре Back-End (Node.js, Prisma) для создания полноценных SaaS-продуктов.',
    'about.p2':
      'Имею опыт преобразования дизайнов Figma в быстрые и масштабируемые веб-приложения, сочетая чистый код со сложной бизнес-логикой. В настоящее время учусь на факультете анализа и разработки систем в FATEC.',
    'about.p3':
      'Работал над более чем 15 корпоративными проектами и в качестве международного фрилансера. Объединяю UI/UX дизайн и технические решения, тесно сотрудничая с Product Owner-ами и QA в Agile-командах, руководя сквозной технической разработкой.',
    'about.stats.projects': 'B2B и B2C Проекты',
    'about.stats.years': 'Лет Опыта',
    'gallery.title': 'Галерея',
    'gallery.subtitle': 'Моменты и Закулисье',
    'nav.home': 'Главная',
    'nav.about': 'Обо мне',
    'nav.projects': 'Проекты',
    'nav.portfolio': 'Портфолио',
    'nav.courses': 'Курсы',
    'nav.cta': 'Контакт',
    'settings.theme': 'Тема',
    'settings.theme.light': 'Светлый режим',
    'settings.theme.dark': 'Тёмный режим',
    'settings.theme.light.short': 'Светлая',
    'settings.theme.dark.short': 'Тёмная',
    'settings.language': 'Язык',
    'footer.navigation': 'Навигация',
    'footer.contact': 'Контакт',
    'footer.copyright': 'Все права защищены.',
    'footer.changelog.viewAll': 'Все версии →',
    'footer.bio': 'Software Engineer & Full Stack — создание современных цифровых продуктов, от дизайна до архитектуры. Специализация: React, Next.js и TypeScript.',
    'footer.versions': 'Версии',
    'projects.personal': 'Личные',
    'projects.company': 'Компания',
    'projects.university': 'Университет',
    'projects.personal.desc': 'Проекты и Эксперименты',
    'projects.company.desc': 'Профессиональная Работа',
    'projects.university.desc': 'Учебная Работа',
    'projects.title.personal': 'Личные Проекты',
    'projects.title.company': 'Проекты Компании',
    'projects.title.university': 'Университетские Проекты',
    'projects.subtitle.personal': 'Проекты и Эксперименты',
    'projects.subtitle.company': 'Профессиональная Работа',
    'projects.subtitle.university': 'Учебная Работа',
    'projects.empty': 'Проекты ещё не добавлены. Скоро будут!',
    'project.elevenlabs.desc': 'Личный проект, в котором я воссоздал интерфейс ElevenLabs с использованием Next.js, React, TypeScript и Styled-Components. Фокус на воспроизведении дизайна, анимаций и визуального опыта платформы.',
    'project.portfolio.desc': 'Первое личное портфолио, созданное за 1 месяц с адаптивностью и множеством анимаций. Сайт из 3 страниц с профилем, проектами, курсами и сертификатами — интерактивное и подробное резюме.',
    'project.paragrafeado.desc': 'React-проект навигации с фокусом на компонентизацию и маршрутизацию. Чистый интерфейс для просмотра контента с плавной навигацией между страницами.',
    'project.netflix.desc': 'Редизайн Netflix с интеграцией базы данных MySQL. Полные CRUD-операции, подключение через PHP и различные функции управления контентом. Проект при Fatec Mogi das Cruzes.',
    'project.calculadora.desc': 'Продвинутый калькулятор на языке C, более 2 500 строк кода. Совместный проект в Fatec Mogi das Cruzes, от базовых операций до сложных математических функций.',
    'exp.title': 'Опыт',
    'exp.subtitle': 'Стек и Профессиональный Путь',
    'exp.p1': 'Спроектировал и разработал (Front и Back) мульти-тенантные B2B SaaS-платформы для автомобильного сектора, связывающие дилеров, розничных продавцов и сервис-провайдеров. Реализовал сложную логику RBAC, управление гаражами, аукционы, подписки и интеграцию платежей с Pagar.me.',
    'exp.p2': 'Создавал сложные Admin и B2B дашборды для e-commerce, социальных сетей и внутренних инструментов. Разработал системы чата в реальном времени с Firebase и WebSockets, выполнял front-end проекты как международный фрилансер через Upwork для клиентов из США.',
    'exp.stats.corporate': 'Корпоративные Проекты',
    'exp.stats.fullstack': 'Корпоративный Проект (FullStack)',
    'exp.stats.commits': 'Коммиты',
    'exp.stats.certifications': 'Сертификаты',
    'exp.stacks.label': 'Основные Стеки',
    'courses.title': 'Курсы',
    'courses.subtitle': 'Сертификаты и Обучение',
    'courses.count.single': 'курс найден',
    'courses.count.plural': 'курсов найдено',
    'courses.filter.all': 'Все',
    'courses.filter.organization': 'Организация',
    'courses.filter.skills': 'Навыки',
    'courses.hours': 'часов',
    'month.1': 'Январь',
    'month.2': 'Февраль',
    'month.3': 'Март',
    'month.4': 'Апрель',
    'month.5': 'Май',
    'month.6': 'Июнь',
    'month.7': 'Июль',
    'month.8': 'Август',
    'month.9': 'Сентябрь',
    'month.10': 'Октябрь',
    'month.11': 'Ноябрь',
    'month.12': 'Декабрь',
    'date.preposition': ' ',
    'changelog.title': 'Версии',
    'changelog.description': 'Полная история обновлений и улучшений портфолио.',
    'changelog.current': 'текущая',
    'settings.page.title': 'Настройки',
    'settings.page.subtitle': 'Настройте своё взаимодействие с портфолио.',
    'settings.page.tag': 'Настройки и Система',
    'settings.about.title': 'Обо мне',
    'settings.about.bio': 'Full Stack разработчик, увлечённый созданием современных и плавных цифровых решений.',
    'settings.theme.desc': 'Переключайтесь между светлой и тёмной темой.',
    'settings.versions.title': 'История Версий',
    'settings.wip.section': 'Альтернативная Страница',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Посмотреть начальную версию портфолио в разработке.',
    'nav.settings': 'Настройки',
    'who.title': 'Кто я?',
    'who.subtitle': 'Full Stack разработчик',
    'who.bio.p1': 'Мне 22 года, и я всегда был увлечён дизайном, особенно для веба. В начале я много изучал WordPress и Elementor, и сегодня эта страсть только усилилась. Я также очень увлечён английским — слушаю много музыки на английском, и для улучшения навыков, и просто потому что нравится. Я верю, что обучение никогда не останавливается, и это то, что движет мной каждый день.',
    'who.bio.p2': 'Мои софт-скиллы включают быстрое обучение, чёткую коммуникацию, отличную организацию и умение работать под давлением. Мне нравится быть частью важных проектов, и я очень практичен в решении багов, ошибок и проблем — предпочитаю решать быстро и двигаться дальше. Я уже проводил встречи с клиентами, объясняя процесс разработки и ведя беседу. Мне нравится работать в команде — хотя иногда я чувствую себя продуктивнее, фокусируясь в одиночку на конкретной задаче. Также люблю руководить, обучать и делиться знаниями, всегда с уважением и сотрудничеством.',
    'who.bio.p3': 'В повседневной жизни люблю пить кофе за кодом, обожаю котов, иногда играю в игры и хожу в зал. Обожаю остановиться и изучить что-то новое — другой стек, инструмент, новый подход. Это постоянное любопытство — то, что заставляет меня развиваться как разработчика.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Технологии & Профессиональный Опыт',
    'nav.skills': 'Навыки',
    'skills.page.tag': 'Технические Навыки',
    'skills.page.title': 'Skills',
    'skills.page.subtitle': 'Технологии и инструменты, которые я использую ежедневно как разработчик.',
    'skills.page.hint': 'Чем больше блок, тем выше уровень владения технологией.',
    'skills.frontend': 'Front-End',
    'skills.backend': 'Back-End и Базы Данных',
    'skills.devops': 'DevOps и Инструменты',
    'nav.timeline': 'Путь',
    'timeline.page.tag': 'Профессиональная История',
    'timeline.page.title': 'Мой Путь',
    'timeline.page.subtitle': 'Хронология основных этапов моей карьеры разработчика.',
    'timeline.cat.education': 'Образование',
    'timeline.cat.work': 'Работа',
    'timeline.cat.freelance': 'Фриланс',
    'timeline.cat.milestone': 'Веха',
    'timeline.2026.projects': 'Участие в 16+ проектах компании',
    'timeline.2026.projects.desc': 'Работал над 16+ корпоративными проектами: B2B, B2C платформы, дашборды и внутренние инструменты.',
    'timeline.2026.fullstack': 'Изучение структуры SaaS и Full Stack',
    'timeline.2026.fullstack.desc': 'Первые проекты как Full Stack, изучение SaaS, Strapi, SSH, GitHub и Prisma.',
    'timeline.2026.english': 'Самостоятельное изучение английского',
    'timeline.2026.english.desc': 'Продолжение самостоятельного изучения английского. Текущий уровень: B2.',
    'timeline.2025.stack': 'Изучение сложных интеграций и бэкенда',
    'timeline.2025.stack.desc': 'Погружение в JSX, Node.js, сложные интеграции, бэкенд, Pagar.me, Firebase, чат, WebSockets, SaaS.',
    'timeline.2025.hired': 'Принят как Front-End Junior',
    'timeline.2025.hired.desc': '1 октября принят на должность Front-End Junior разработчика после стажировки.',
    'timeline.2025.freela': 'Ещё один фриланс-проект завершён',
    'timeline.2025.freela.desc': 'Завершил ещё один фриланс-проект, закрепив международный опыт.',
    'timeline.2025.english': 'Самостоятельное изучение английского',
    'timeline.2025.english.desc': 'Самостоятельное изучение английского. Текущий уровень: B2.',
    'timeline.2024.intern': 'Начало стажировки Front-End',
    'timeline.2024.intern.desc': '14 октября начал работу в Mestres da Web как стажёр Front-End.',
    'timeline.2024.stack': 'Изучение JS, TS, React, Next и др.',
    'timeline.2024.stack.desc': 'JavaScript, TypeScript, React, Next.js, REST API, Figma, Postman, Asana и Git.',
    'timeline.2024.freela': 'Первый фриланс-проект завершён',
    'timeline.2024.freela.desc': 'Первый фриланс-проект завершён через Upwork для международного клиента.',
    'timeline.2024.courses': 'Курсы завершены',
    'timeline.2024.courses.desc': 'Завершил несколько курсов и сертификаций.',
    'timeline.2024.english': 'Окончание курса английского',
    'timeline.2024.english.desc': 'Завершил формальный курс английского. Достигнутый уровень: B1.',
    'timeline.2023.fatec': 'Начало в FATEC MC — ADS',
    'timeline.2023.fatec.desc': 'Поступил на программу Анализа и Разработки Систем в FATEC Mogi das Cruzes.',
    'timeline.2023.courses': 'Курсы завершены',
    'timeline.2023.courses.desc': 'Завершил курсы веб-разработки и фронтенда.',
    'timeline.2023.frameworks': 'Изучение Bootstrap, jQuery, React и JS',
    'timeline.2023.frameworks.desc': 'Углубление в фреймворки: Bootstrap, jQuery, React и продвинутый JavaScript.',
    'timeline.2023.english': 'Самостоятельное изучение английского',
    'timeline.2023.english.desc': 'Самостоятельное изучение английского. Текущий уровень: A2.',
    'timeline.2022.code': 'Первые строки кода',
    'timeline.2022.code.desc': 'Написал первые строки кода на HTML, CSS и JavaScript. Начало всего.',
    'timeline.2022.danki': 'Курс Danki Code приобретён',
    'timeline.2022.danki.desc': 'Приобретён курс Danki Code: полный Front-End, полная веб-разработка и Web Design Express.',
    'timeline.2022.english': 'Начало курса английского — Cultura Inglesa',
    'timeline.2022.english.desc': 'Начал курс английского в Cultura Inglesa. Начальный уровень: A1.',
    'timeline.2021.sold': 'Первый проданный проект',
    'timeline.2021.sold.desc': 'Первый проданный проект на WordPress с Elementor, размещённый на HostGator.',
    'timeline.2021.shopify': 'Изучение Shopify',
    'timeline.2021.shopify.desc': 'Изучение платформы Shopify для создания интернет-магазинов.',
    'timeline.2020.wordpress': 'Изучение WordPress (Elementor)',
    'timeline.2020.wordpress.desc': 'Первые шаги в веб-разработке, изучение WordPress с Elementor.',
    'timeline.2020.hosting': 'Изучение хостингов (SSH, домены)',
    'timeline.2020.hosting.desc': 'Изучение хостингов, SSH, доменов и веб-инфраструктуры.',
    'timeline.2020.webdesign': 'Изучение веб-дизайна (концепции)',
    'timeline.2020.webdesign.desc': 'Изучение концепций веб-дизайна, макетов, цветов и типографики.',
    'github.viewProfile': 'Профиль',
    'github.totalCommits': 'Всего Коммитов',
    'github.lastYear': 'За Год',
    'github.activeYears': 'Активных Лет',
    'github.contributions': 'Вклад',
    'github.inLastYear': 'за последний год',
    'github.contributionsLabel': 'вкладов',
    'github.less': 'Меньше',
    'github.more': 'Больше',
    'nav.aboutme': 'Обо мне',
    'nav.cases': 'Кейсы',
    'nav.testimonials': 'Отзывы',
    'cases.page.tag': 'Кейсы',
    'cases.page.title': 'Кейсы',
    'cases.page.subtitle': 'Реальные проблемы, с которыми я столкнулся, и как я их решил. Каждый кейс показывает техническое мышление за каждой доставкой.',
    'cases.section.problem': 'Проблема',
    'cases.section.approach': 'Подход',
    'cases.section.result': 'Результат',
    'cases.saas.title': 'Мультитенантные B2B SaaS Платформы',
    'cases.saas.problem': 'Клиенту нужна была платформа, соединяющая дилеров, розничных продавцов и поставщиков услуг в автомобильном секторе с изоляцией данных и сложными правами доступа.',
    'cases.saas.approach': 'Я спроектировал мультитенантное решение с гранулярным RBAC, используя Next.js на фронте и Node.js + Prisma на бэке. Реализовал управление гаражами, аукционы, подписки и интеграцию платежей.',
    'cases.saas.result': 'Платформа работает в продакшене с несколькими клиентами одновременно. RBAC обеспечивает точный контроль прав доступа.',
    'cases.saas.metric1.label': 'Корпоративные Проекты',
    'cases.saas.metric2.label': 'Контроль Доступа',
    'cases.saas.metric3.label': 'Архитектура',
    'cases.chat.title': 'Система Чата в Реальном Времени',
    'cases.chat.problem': 'Один из корпоративных проектов требовал общения в реальном времени. Решение должно быть производительным и масштабируемым.',
    'cases.chat.approach': 'Я реализовал чат с Firebase Realtime Database и WebSockets. Создал кастомные хуки для управления соединениями и присутствием.',
    'cases.chat.result': 'Чат в продакшене с задержкой менее 100мс. Поддержка индивидуальных и групповых бесед.',
    'cases.chat.metric1.label': 'Доставка',
    'cases.chat.metric2.label': 'Протокол',
    'cases.chat.metric3.label': 'Задержка',
    'cases.dashboard.title': 'Сложные Admin & B2B Дашборды',
    'cases.dashboard.problem': 'Несколько проектов требовали сложных административных дашбордов для e-commerce, соцсетей и внутренних инструментов.',
    'cases.dashboard.approach': 'Я разработал систему переиспользуемых компонентов на React + TypeScript + Styled-Components.',
    'cases.dashboard.result': 'Более 5 дашбордов высокой сложности доставлено. Дизайн-система ускорила разработку.',
    'cases.dashboard.metric1.label': 'Дашборды',
    'cases.dashboard.metric2.label': 'Сегменты',
    'cases.dashboard.metric3.label': 'Конверсия',
    'cases.freelance.title': 'Международный Фриланс через Upwork',
    'cases.freelance.problem': 'Клиенты в США искали надёжного front-end разработчика с коммуникацией на английском.',
    'cases.freelance.approach': 'Я работал фрилансером через Upwork, проводя встречи на английском и доставляя проекты на Next.js, TypeScript и Vercel.',
    'cases.freelance.result': 'Все проекты доставлены в срок с максимальной оценкой.',
    'cases.freelance.metric1.label': 'Клиенты',
    'cases.freelance.metric2.label': 'Платформа',
    'cases.freelance.metric3.label': 'Удовлетворённость',
    'testimonials.page.tag': 'Отзывы',
    'testimonials.page.title': 'Что говорят обо мне',
    'testimonials.page.subtitle': 'Отзывы руководителей, коллег и клиентов, с которыми я работал.',
    'testimonials.manager.quote': 'Артур демонстрирует исключительные технические способности и впечатляющую проактивность. Он руководил сложными внедрениями автономно.',
    'testimonials.client.quote': 'Excellent developer. Arthur understood our requirements quickly and delivered a polished product. His communication was clear and professional throughout the project.',
    'testimonials.colleague.quote': 'Работать с Артуром очень продуктивно. У него сильное техническое видение, он помогает команде быстро исправлять баги.'
  },
  es: {
    'hero.greeting': 'Hola, soy',
    'hero.role': 'Software Engineer & Full Stack',
    'hero.description':
      'Construyendo experiencias digitales modernas, fluidas y centradas en la excelencia del producto, del diseño elegante a la arquitectura robusta.',
    'hero.btn.primary': 'Continuar',
    'hero.btn.secondary': 'Contáctame',
    'about.title': 'Sobre mí',
    'about.subtitle': 'Ingeniero de Software & Full Stack',
    'about.p1':
      'Desarrollador de Software con fuerte especialización en Front-End (React.js, Next.js, TypeScript) y experiencia sólida en arquitectura Back-End (Node.js, Prisma) para la construcción de productos SaaS completos.',
    'about.p2':
      'Transformo diseños de Figma en aplicaciones web rápidas y escalables, uniendo código limpio con reglas de negocio complejas. Actualmente estudio Análisis y Desarrollo de Sistemas en la FATEC Mogi das Cruzes.',
    'about.p3':
      'He trabajado en más de 15 proyectos corporativos y como freelancer internacional. Hago de puente entre el diseño UI/UX y las soluciones técnicas, colaborando con Product Owners y QAs en equipos Ágiles.',
    'about.stats.projects': 'Proyectos B2B & B2C',
    'about.stats.years': 'Años de Exp',
    'gallery.title': 'Galería',
    'gallery.subtitle': 'Momentos & Backstage',
    'nav.home': 'Inicio',
    'nav.about': 'Sobre mí',
    'nav.projects': 'Proyectos',
    'nav.portfolio': 'Portafolio',
    'nav.courses': 'Cursos',
    'nav.cta': 'Contacto',
    'settings.theme': 'Tema',
    'settings.theme.light': 'Modo Claro',
    'settings.theme.dark': 'Modo Oscuro',
    'settings.theme.light.short': 'Claro',
    'settings.theme.dark.short': 'Oscuro',
    'settings.language': 'Idioma',
    'footer.navigation': 'Navegación',
    'footer.contact': 'Contacto',
    'footer.copyright': 'Todos los derechos reservados.',
    'footer.changelog.viewAll': 'Ver todas las versiones →',
    'footer.bio': 'Software Engineer & Full Stack — construyendo productos digitales modernos, del diseño a la arquitectura. Enfocado en React, Next.js y TypeScript.',
    'footer.versions': 'Versiones',
    'projects.personal': 'Personales',
    'projects.company': 'Empresa',
    'projects.university': 'Universidad',
    'projects.personal.desc': 'Proyectos & Experimentos',
    'projects.company.desc': 'Trabajo Profesional',
    'projects.university.desc': 'Trabajo Académico',
    'projects.title.personal': 'Proyectos Personales',
    'projects.title.company': 'Proyectos de Empresa',
    'projects.title.university': 'Proyectos Universitarios',
    'projects.subtitle.personal': 'Proyectos & Experimentos',
    'projects.subtitle.company': 'Trabajos Profesionales',
    'projects.subtitle.university': 'Trabajos Académicos',
    'projects.empty': 'Ningún proyecto añadido aún. ¡Próximamente!',
    'project.elevenlabs.desc': 'Proyecto personal donde recreé la interfaz de ElevenLabs usando Next.js, React, TypeScript y Styled-Components. Enfocado en replicar el diseño, animaciones y experiencia visual completa de la plataforma.',
    'project.portfolio.desc': 'Primer portfolio personal, desarrollado en 1 mes con responsividad y varias animaciones. Sitio con 3 páginas mostrando perfil, proyectos, cursos y certificaciones.',
    'project.paragrafeado.desc': 'Proyecto de navegación en React centrado en componentización y enrutamiento. Interfaz limpia para exploración de contenido con navegación fluida entre páginas.',
    'project.netflix.desc': 'Reinterpretación de Netflix con integración a base de datos MySQL. Implementación de operaciones CRUD completas, conexión vía PHP y diversas funcionalidades de gestión de contenido.',
    'project.calculadora.desc': 'Calculadora avanzada desarrollada en lenguaje C con más de 2.500 líneas de código. Proyecto colaborativo realizado en la Fatec Mogi das Cruzes.',
    'exp.title': 'Experiencia',
    'exp.subtitle': 'Stacks & Vivencia Profesional',
    'exp.p1': 'Diseñé y desarrollé (Front y Back) plataformas SaaS B2B Multi-tenant para el sector automotriz, conectando concesionarios, comerciantes y proveedores de servicios. Implementé lógicas complejas de RBAC, gestión de garajes, subastas, planes de suscripción e integración de pagos con Pagar.me.',
    'exp.p2': 'Construí dashboards Admin y B2B complejos para e-commerce, redes sociales y herramientas internas. Creé sistemas de chat en tiempo real con Firebase y WebSockets, además de entregar proyectos front-end como freelancer internacional vía Upwork para clientes en EE.UU.',
    'exp.stats.corporate': 'Proyectos Corporativos',
    'exp.stats.fullstack': 'Proyecto Corporativo (FullStack)',
    'exp.stats.commits': 'Commits',
    'exp.stats.certifications': 'Certificaciones',
    'exp.stacks.label': 'Stacks Principales',
    'courses.title': 'Cursos',
    'courses.subtitle': 'Certificaciones & Aprendizaje',
    'courses.count.single': 'curso encontrado',
    'courses.count.plural': 'cursos encontrados',
    'courses.filter.all': 'Todos',
    'courses.filter.organization': 'Organización',
    'courses.filter.skills': 'Competencias',
    'courses.hours': 'horas',
    'month.1': 'Enero',
    'month.2': 'Febrero',
    'month.3': 'Marzo',
    'month.4': 'Abril',
    'month.5': 'Mayo',
    'month.6': 'Junio',
    'month.7': 'Julio',
    'month.8': 'Agosto',
    'month.9': 'Septiembre',
    'month.10': 'Octubre',
    'month.11': 'Noviembre',
    'month.12': 'Diciembre',
    'date.preposition': ' de ',
    'changelog.title': 'Versiones',
    'changelog.description': 'Historial completo de actualizaciones y mejoras del portfolio.',
    'changelog.current': 'actual',
    'settings.page.title': 'Configuración',
    'settings.page.subtitle': 'Personaliza tu experiencia en el portfolio.',
    'settings.page.tag': 'Preferencias y Sistema',
    'settings.about.title': 'Sobre mí',
    'settings.about.bio': 'Desarrollador Full Stack apasionado por crear experiencias digitales modernas y fluidas.',
    'settings.theme.desc': 'Alterna entre los modos claro y oscuro.',
    'settings.versions.title': 'Historial de Versiones',
    'settings.wip.section': 'Página Alternativa',
    'settings.wip.title': 'Under Development',
    'settings.wip.desc': 'Visualiza la versión inicial del portfolio, en construcción.',
    'nav.settings': 'Configuración',
    'who.title': '¿Quién soy?',
    'who.subtitle': 'Desarrollador Full Stack',
    'who.bio.p1': 'Tengo 22 años y siempre me apasionó el diseño, especialmente para la web. Al principio estudié mucho WordPress y Elementor, y hoy esa pasión solo ha crecido. También me encanta el inglés — escucho mucha música en inglés, tanto para mejorar como por puro gusto. Creo que el aprendizaje nunca se detiene, y eso es lo que me impulsa cada día.',
    'who.bio.p2': 'Mis soft skills incluyen aprendizaje rápido, comunicación clara, excelente organización y gusto por trabajar bajo presión. Me gusta formar parte de proyectos importantes y soy muy práctico a la hora de resolver bugs, errores y problemas — prefiero resolver rápido y seguir adelante. Ya he conducido reuniones con clientes, explicando el desarrollo y liderando la conversación. Me gusta trabajar en equipo — aunque a veces me siento más productivo enfocándome solo en alguna actualización específica. También me gusta liderar, enseñar y compartir conocimiento, siempre con respeto y colaboración.',
    'who.bio.p3': 'En el día a día, me gusta tomar un café mientras programo, soy fan de los gatos, me gusta jugar de vez en cuando y entrenar en el gimnasio. Me encanta parar todo para aprender algo nuevo — un stack diferente, una herramienta, un enfoque nuevo. Esta curiosidad constante es lo que me mantiene evolucionando como desarrollador.',
    'stacks.title': 'Stacks & Background',
    'stacks.subtitle': 'Tecnologías & Experiencia Profesional',
    'nav.skills': 'Habilidades',
    'skills.page.tag': 'Competencias Técnicas',
    'skills.page.title': 'Skills',
    'skills.page.subtitle': 'Las tecnologías y herramientas que uso a diario como desarrollador.',
    'skills.page.hint': 'Cuanto mayor sea el bloque, mayor es el dominio de la tecnología.',
    'skills.frontend': 'Front-End',
    'skills.backend': 'Back-End & Bases de Datos',
    'skills.devops': 'DevOps & Herramientas',
    'nav.timeline': 'Trayectoria',
    'timeline.page.tag': 'Historial Profesional',
    'timeline.page.title': 'Mi Trayectoria',
    'timeline.page.subtitle': 'Una línea de tiempo con los principales hitos de mi carrera como desarrollador.',
    'timeline.cat.education': 'Educación',
    'timeline.cat.work': 'Trabajo',
    'timeline.cat.freelance': 'Freelance',
    'timeline.cat.milestone': 'Hito',
    'timeline.2026.projects': 'Participación en +16 Proyectos en la Empresa',
    'timeline.2026.projects.desc': 'Trabajé en más de 16 proyectos corporativos incluyendo plataformas B2B, B2C, dashboards y herramientas internas.',
    'timeline.2026.fullstack': 'Estudiando Estructura SaaS & Full Stack',
    'timeline.2026.fullstack.desc': 'Primeros proyectos como Full Stack, estudiando SaaS, Strapi, SSH, GitHub y Prisma.',
    'timeline.2026.english': 'Estudiando Inglés por Cuenta Propia',
    'timeline.2026.english.desc': 'Continuando estudios de inglés de forma autodidacta. Nivel actual: B2.',
    'timeline.2025.stack': 'Estudiando Integraciones Pesadas & Backend',
    'timeline.2025.stack.desc': 'Inmersión en JSX, Node.js, integraciones pesadas, backend, Pagar.me, Firebase, chat en vivo, WebSockets, SaaS.',
    'timeline.2025.hired': 'Contratado como Front-End Junior',
    'timeline.2025.hired.desc': 'El 1 de octubre, contratado como desarrollador Front-End Junior tras la pasantía.',
    'timeline.2025.freela': 'Otro Proyecto Freelance Finalizado',
    'timeline.2025.freela.desc': 'Finalicé otro proyecto freelance, consolidando experiencia en entregas internacionales.',
    'timeline.2025.english': 'Estudiando Inglés por Cuenta Propia',
    'timeline.2025.english.desc': 'Estudios autodidactas de inglés. Nivel actual: B2.',
    'timeline.2024.intern': 'Inicio como Pasante Front-End',
    'timeline.2024.intern.desc': 'El 14 de octubre, comencé a trabajar en Mestres da Web como pasante Front-End.',
    'timeline.2024.stack': 'Estudiando JS, TS, React, Next & Más',
    'timeline.2024.stack.desc': 'JavaScript, TypeScript, React, Next.js, API REST, Figma, Postman, Asana y Git.',
    'timeline.2024.freela': 'Primer Proyecto Freelance Finalizado',
    'timeline.2024.freela.desc': 'Primer proyecto freelance finalizado vía Upwork para un cliente internacional.',
    'timeline.2024.courses': 'Cursos Finalizados',
    'timeline.2024.courses.desc': 'Finalicé varios cursos y certificaciones.',
    'timeline.2024.english': 'Salí del Curso de Inglés',
    'timeline.2024.english.desc': 'Terminé el curso formal de inglés. Nivel alcanzado: B1.',
    'timeline.2023.fatec': 'Inicio en FATEC MC — ADS',
    'timeline.2023.fatec.desc': 'Ingresé en Análisis y Desarrollo de Sistemas en la FATEC Mogi das Cruzes.',
    'timeline.2023.courses': 'Cursos Finalizados',
    'timeline.2023.courses.desc': 'Finalicé cursos de desarrollo web y front-end.',
    'timeline.2023.frameworks': 'Estudiando Bootstrap, jQuery, React & JS',
    'timeline.2023.frameworks.desc': 'Profundización en frameworks: Bootstrap, jQuery, React y JavaScript avanzado.',
    'timeline.2023.english': 'Estudiando Inglés por Cuenta Propia',
    'timeline.2023.english.desc': 'Estudios autodidactas de inglés. Nivel actual: A2.',
    'timeline.2022.code': 'Primeras Líneas de Código',
    'timeline.2022.code.desc': 'Escribí mis primeras líneas de código en HTML, CSS y JavaScript. El comienzo de todo.',
    'timeline.2022.danki': 'Curso Danki Code Adquirido',
    'timeline.2022.danki.desc': 'Adquirí el curso Danki Code: Front-End Completo, Desarrollo Web Completo y Web Design Express.',
    'timeline.2022.english': 'Inicio Curso de Inglés — Cultura Inglesa',
    'timeline.2022.english.desc': 'Comencé el curso de inglés en Cultura Inglesa. Nivel inicial: A1.',
    'timeline.2021.sold': 'Primer Proyecto Vendido',
    'timeline.2021.sold.desc': 'Mi primer proyecto vendido usando WordPress con Elementor, alojado en HostGator.',
    'timeline.2021.shopify': 'Estudiando Shopify',
    'timeline.2021.shopify.desc': 'Estudiando la plataforma Shopify para creación de e-commerces.',
    'timeline.2020.wordpress': 'Estudiando WordPress (Elementor)',
    'timeline.2020.wordpress.desc': 'Primeros pasos en el desarrollo web, aprendiendo WordPress con Elementor.',
    'timeline.2020.hosting': 'Estudiando Hospedajes (SSH, Dominios)',
    'timeline.2020.hosting.desc': 'Aprendiendo sobre hospedajes, SSH, dominios e infraestructura web.',
    'timeline.2020.webdesign': 'Estudiando Web Design (Conceptos)',
    'timeline.2020.webdesign.desc': 'Estudiando conceptos de web design, layout, colores y tipografía.',
    'github.viewProfile': 'Ver Perfil',
    'github.totalCommits': 'Commits Totales',
    'github.lastYear': 'Último Año',
    'github.activeYears': 'Años Activos',
    'github.contributions': 'Contribuciones',
    'github.inLastYear': 'en el último año',
    'github.contributionsLabel': 'contribuciones',
    'github.less': 'Menos',
    'github.more': 'Más',
    'nav.aboutme': 'Sobre Mí',
    'nav.cases': 'Casos',
    'nav.testimonials': 'Testimonios',
    'cases.page.tag': 'Estudios de Caso',
    'cases.page.title': 'Casos',
    'cases.page.subtitle': 'Problemas reales que enfrenté y cómo los resolví. Cada caso muestra el razonamiento técnico detrás de las entregas.',
    'cases.section.problem': 'El Problema',
    'cases.section.approach': 'El Enfoque',
    'cases.section.result': 'El Resultado',
    'cases.saas.title': 'Plataformas SaaS Multi-tenant B2B',
    'cases.saas.problem': 'El cliente necesitaba una plataforma conectando concesionarios, minoristas y proveedores de servicios en el sector automotriz con aislamiento de datos y permisos complejos.',
    'cases.saas.approach': 'Diseñé una solución Multi-tenant con RBAC granular usando Next.js y Node.js + Prisma. Implementé gestión de garajes, subastas, suscripciones e integración de pagos con Pagar.me.',
    'cases.saas.result': 'Plataforma entregada y operando en producción con múltiples clientes simultáneos. El RBAC permite control fino de permisos por rol.',
    'cases.saas.metric1.label': 'Proyectos Corporativos',
    'cases.saas.metric2.label': 'Control de Acceso',
    'cases.saas.metric3.label': 'Arquitectura',
    'cases.chat.title': 'Sistema de Chat en Tiempo Real',
    'cases.chat.problem': 'Uno de los proyectos corporativos requería comunicación en tiempo real. La solución debía ser eficiente, escalable y mantener el historial de mensajes.',
    'cases.chat.approach': 'Implementé un chat con Firebase Realtime Database y WebSockets. Creé hooks personalizados para gestionar conexiones y presencia en línea.',
    'cases.chat.result': 'Chat en producción con latencia inferior a 100ms. Soporte para conversaciones individuales y grupales.',
    'cases.chat.metric1.label': 'Entrega',
    'cases.chat.metric2.label': 'Protocolo',
    'cases.chat.metric3.label': 'Latencia',
    'cases.dashboard.title': 'Dashboards Admin & B2B Complejos',
    'cases.dashboard.problem': 'Múltiples proyectos requerían dashboards administrativos complejos para e-commerce, redes sociales y herramientas internas.',
    'cases.dashboard.approach': 'Desarrollé un sistema de componentes reutilizables en React + TypeScript + Styled-Components.',
    'cases.dashboard.result': 'Más de 5 dashboards de alta complejidad entregados. El design system redujo el tiempo de desarrollo.',
    'cases.dashboard.metric1.label': 'Dashboards Entregados',
    'cases.dashboard.metric2.label': 'Segmentos',
    'cases.dashboard.metric3.label': 'Conversión',
    'cases.freelance.title': 'Freelance Internacional via Upwork',
    'cases.freelance.problem': 'Clientes en EE.UU. necesitaban un desarrollador front-end confiable con comunicación en inglés y plazos ajustados.',
    'cases.freelance.approach': 'Trabajé como freelancer vía Upwork, liderando reuniones en inglés y entregando proyectos con Next.js, TypeScript y Vercel.',
    'cases.freelance.result': 'Todos los proyectos entregados a tiempo con evaluación máxima.',
    'cases.freelance.metric1.label': 'Clientes',
    'cases.freelance.metric2.label': 'Plataforma',
    'cases.freelance.metric3.label': 'Satisfacción',
    'testimonials.page.tag': 'Testimonios',
    'testimonials.page.title': 'Lo que dicen de mí',
    'testimonials.page.subtitle': 'Feedback de gestores, colegas y clientes con quienes tuve el placer de trabajar.',
    'testimonials.manager.quote': 'Arthur demuestra una capacidad técnica excepcional y una proactividad impresionante. Lideró implementaciones complejas con autonomía.',
    'testimonials.client.quote': 'Excellent developer. Arthur understood our requirements quickly and delivered a polished product. His communication was clear and professional throughout the project.',
    'testimonials.colleague.quote': 'Trabajar con Arthur es muy productivo. Tiene una visión técnica fuerte, ayuda al equipo a resolver bugs rápidamente y siempre comparte conocimiento.'
  },
} as const;

type DictionaryKeys = keyof typeof dictionaries.pt;

const getTranslation = (lang: Language, key: DictionaryKeys) => {
  return dictionaries[lang][key] || key;
};

interface LanguageContextData {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: DictionaryKeys) => string;
}

const LanguageContext = createContext<LanguageContextData>({
  language: 'pt',
  toggleLanguage: () => {},
  setLanguage: () => {},
  t: (key: DictionaryKeys) => getTranslation('pt', key),
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pt');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('@Portfolio:lang') as Language;
    if (savedLanguage) {
      setLanguage(savedLanguage);
    } else {
      const nav = navigator.language;
      if (nav.startsWith('fr')) setLanguage('fr');
      else if (nav.startsWith('ru')) setLanguage('ru');
      else if (nav.startsWith('es')) setLanguage('es');
      else if (nav.startsWith('en')) setLanguage('en');
      else setLanguage('pt');
    }
  }, []);

  const toggleLanguage = () => {
    const newLang = language === 'pt' ? 'en' : 'pt';
    setLanguage(newLang);
    localStorage.setItem('@Portfolio:lang', newLang);
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('@Portfolio:lang', lang);
  };

  const t = (key: DictionaryKeys) => getTranslation(language, key);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
