export interface ProjectPlatform {
  title: string;
  descriptionKey: string;
  images?: string[];
  tags: string[];
  roleKey?: string;
  featuresKey?: string;
}

export type ProjectType =
  | 'ecommerce'
  | 'dashboard'
  | 'landing'
  | 'saas'
  | 'other';
export type ProjectPlatformType = 'web' | 'app';

export interface ProjectItem {
  title: string;
  descriptionKey: string;
  images?: string[];
  tags: string[];
  link?: string;
  hidden?: boolean;
  featured?: boolean;
  roleKey?: string;
  durationKey?: string;
  highlightKey?: string;
  platforms?: ProjectPlatform[];
  year: number;
  month?: number;
  projectType: ProjectType;
  platformType: ProjectPlatformType;
}

export const COMPANY_PROJECTS: ProjectItem[] = [
  {
    title: 'AVS',
    descriptionKey: 'project.avs.desc',
    featured: true,
    year: 2026,
    month: 8,
    projectType: 'saas',
    platformType: 'web',
    images: [
      '/projects/avs/1.png',
      '/projects/avs/2.png',
      '/projects/avs/3.png',
      '/projects/avs/4.png',
      '/projects/avs/5.png',
      '/projects/avs/6.png',
      '/projects/avs/7.png',
      '/projects/avs/8.png',
      '/projects/avs/9.png',
    ],
    tags: [
      'Next.js 15',
      'React 18',
      'TypeScript',
      'Styled-Components',
      'React Query',
      'Recharts',
      'Axios',
      'Yup',
      'React Hook Form',
    ],
    roleKey: 'project.avs.role',
    durationKey: 'project.avs.duration',
    highlightKey: 'project.avs.highlight',
  },
  {
    title: 'Certeza que Tem',
    descriptionKey: 'project.cqt.desc',
    featured: true,
    year: 2026,
    month: 7,
    projectType: 'ecommerce',
    platformType: 'web',
    images: [
      '/projects/certeza-cliente/1.png',
      '/projects/certeza-cliente/2.png',
      '/projects/certeza-master/1.png',
      '/projects/certeza-seller/1.png',
    ],
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'Styled-Components',
      'Tailwind CSS',
      'MUI',
      'Chart.js',
      'Firebase',
      'Pagarme',
      'J&T Express',
    ],
    roleKey: 'project.cqt.role',
    durationKey: 'project.cqt.duration',
    highlightKey: 'project.cqt.highlight',
    platforms: [
      {
        title: 'Certeza que Tem Web Cliente',
        descriptionKey: 'project.cqt.client.desc',
        images: [
          '/projects/certeza-cliente/1.png',
          '/projects/certeza-cliente/2.png',
          '/projects/certeza-cliente/3.png',
          '/projects/certeza-cliente/4.png',
        ],
        tags: [
          'Next.js 16',
          'React 18',
          'TypeScript',
          'Styled-Components',
          'React Query',
          'Chart.js',
          'Firebase',
          'Pagarme',
          'J&T Express',
          'QRCode',
        ],
        roleKey: 'project.cqt.client.role',
        featuresKey: 'project.cqt.client.features',
      },
      {
        title: 'Certeza que Tem Web Master',
        descriptionKey: 'project.cqt.master.desc',
        images: [
          '/projects/certeza-master/1.png',
          '/projects/certeza-master/2.png',
          '/projects/certeza-master/3.png',
          '/projects/certeza-master/4.png',
          '/projects/certeza-master/5.png',
        ],
        tags: [
          'Next.js 15',
          'React 19',
          'TypeScript',
          'Styled-Components',
          'Tailwind CSS 4',
          'React Query',
          'Chart.js',
          'Firebase',
        ],
        roleKey: 'project.cqt.master.role',
        featuresKey: 'project.cqt.master.features',
      },
      {
        title: 'Certeza que Tem Web Seller',
        descriptionKey: 'project.cqt.seller.desc',
        images: [
          '/projects/certeza-seller/1.png',
          '/projects/certeza-seller/2.png',
          '/projects/certeza-seller/3.png',
          '/projects/certeza-seller/4.png',
          '/projects/certeza-seller/5.png',
          '/projects/certeza-seller/6.png',
        ],
        tags: [
          'Next.js 15',
          'React 19',
          'TypeScript',
          'Styled-Components',
          'MUI 6',
          'Chart.js',
          'Swiper',
        ],
        roleKey: 'project.cqt.seller.role',
        featuresKey: 'project.cqt.seller.features',
      },
    ],
  },
  {
    title: 'X-Mandu',
    descriptionKey: 'project.xmandu.desc',
    featured: true,
    year: 2025,
    month: 1,
    projectType: 'ecommerce',
    platformType: 'web',
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'Styled-Components',
      'MUI',
      'Chart.js',
      'Swiper',
      'QRCode',
    ],
    roleKey: 'project.xmandu.role',
    durationKey: 'project.xmandu.duration',
    highlightKey: 'project.xmandu.highlight',
    platforms: [
      {
        title: 'X-Mandu Web Prestador',
        descriptionKey: 'project.xmandu.prestador.desc',
        tags: [
          'Next.js 15',
          'React 18',
          'TypeScript',
          'Styled-Components',
          'Chart.js',
          'Lucide',
          'QRCode',
        ],
        roleKey: 'project.xmandu.prestador.role',
        featuresKey: 'project.xmandu.prestador.features',
      },
      {
        title: 'X-Mandu Web Lojista',
        descriptionKey: 'project.xmandu.lojista.desc',
        tags: [
          'Next.js 15',
          'React 19',
          'TypeScript',
          'Styled-Components',
          'MUI 6',
          'Chart.js',
          'Swiper',
        ],
        roleKey: 'project.xmandu.lojista.role',
        featuresKey: 'project.xmandu.lojista.features',
      },
      {
        title: 'X-Mandu Web Master',
        descriptionKey: 'project.xmandu.master.desc',
        tags: [
          'Next.js 15',
          'React 18',
          'TypeScript',
          'Styled-Components',
          'Chart.js',
          'react-to-print',
        ],
        roleKey: 'project.xmandu.master.role',
        featuresKey: 'project.xmandu.master.features',
      },
    ],
  },
  {
    title: 'Pop Gov',
    descriptionKey: 'project.popgov.desc',
    featured: true,
    year: 2025,
    month: 11,
    projectType: 'dashboard',
    platformType: 'web',
    images: [
      '/projects/popgov/1.png',
      '/projects/popgov/2.png',
      '/projects/popgov/3.png',
      '/projects/popgov/4.png',
      '/projects/popgov/5.png',
      '/projects/popgov/6.png',
      '/projects/popgov/7.png',
    ],
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'Styled-Components',
      'Recharts',
      'jsPDF',
      'html2canvas',
      'react-dropzone',
      'Swiper',
    ],
    roleKey: 'project.popgov.role',
    durationKey: 'project.popgov.duration',
    highlightKey: 'project.popgov.highlight',
  },
  {
    title: 'Edugest',
    descriptionKey: 'project.edugest.desc',
    year: 2025,
    month: 10,
    projectType: 'dashboard',
    platformType: 'web',
    images: [
      '/projects/edugest/1.png',
      '/projects/edugest/2.png',
      '/projects/edugest/3.png',
      '/projects/edugest/4.png',
      '/projects/edugest/5.png',
    ],
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'Styled-Components',
      'Radix UI',
      'Recharts',
      'Chart.js',
      'React Query',
    ],
    roleKey: 'project.edugest.role',
    durationKey: 'project.edugest.duration',
    highlightKey: 'project.edugest.highlight',
  },
  {
    title: 'Impulsse',
    descriptionKey: 'project.impulsse.desc',
    year: 2024,
    month: 12,
    projectType: 'dashboard',
    platformType: 'web',
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'Styled-Components',
      'Tailwind CSS',
      'Chart.js',
      'Draft.js',
      'Next Auth',
      'Swiper',
    ],
    roleKey: 'project.impulsse.role',
    durationKey: 'project.impulsse.duration',
    highlightKey: 'project.impulsse.highlight',
  },
  {
    title: 'GoTasks',
    descriptionKey: 'project.gotasks.desc',
    featured: true,
    year: 2025,
    month: 11,
    projectType: 'landing',
    platformType: 'web',
    images: [
      '/projects/gotasks/1.png',
      '/projects/gotasks/2.png',
      '/projects/gotasks/3.png',
      '/projects/gotasks/4.png',
    ],
    tags: ['Next.js', 'React', 'TypeScript', 'Styled-Components', 'QRCode'],
    roleKey: 'project.gotasks.role',
    durationKey: 'project.gotasks.duration',
    highlightKey: 'project.gotasks.highlight',
  },
  {
    title: 'GTI',
    descriptionKey: 'project.gti.desc',
    featured: true,
    year: 2025,
    month: 1,
    projectType: 'saas',
    platformType: 'web',
    tags: [
      'Next.js',
      'React',
      'React Native',
      'Expo',
      'TypeScript',
      'Styled-Components',
      'Tailwind CSS',
      'MUI',
      'ApexCharts',
      'Chart.js',
      'Framer Motion',
      'React Query',
    ],
    roleKey: 'project.gti.role',
    durationKey: 'project.gti.duration',
    highlightKey: 'project.gti.highlight',
    platforms: [
      {
        title: 'GTI Web Centro de Distribuição',
        descriptionKey: 'project.gti.cd.desc',
        tags: [
          'Next.js 15',
          'React 18',
          'TypeScript',
          'Styled-Components',
          'Tailwind CSS',
          'ApexCharts',
          'React Query',
        ],
        roleKey: 'project.gti.cd.role',
        featuresKey: 'project.gti.cd.features',
      },
      {
        title: 'GTI Web Ponto de Coleta',
        descriptionKey: 'project.gti.ponto.desc',
        tags: [
          'Next.js 15',
          'React 18',
          'TypeScript',
          'Styled-Components',
          'Framer Motion',
          'React Query',
          'React Select',
        ],
        roleKey: 'project.gti.ponto.role',
        featuresKey: 'project.gti.ponto.features',
      },
      {
        title: 'GTI Web Master',
        descriptionKey: 'project.gti.master.desc',
        tags: [
          'Next.js 15',
          'React 18',
          'TypeScript',
          'Styled-Components',
          'MUI 6',
          'Chart.js',
          'React Query',
        ],
        roleKey: 'project.gti.master.role',
        featuresKey: 'project.gti.master.features',
      },
      {
        title: 'GTI Web Seller',
        descriptionKey: 'project.gti.seller.desc',
        tags: [
          'Next.js 15',
          'React 19',
          'TypeScript',
          'Tailwind CSS 4',
          'Recharts',
          'Framer Motion',
        ],
        roleKey: 'project.gti.seller.role',
        featuresKey: 'project.gti.seller.features',
      },
      {
        title: 'GTI App Entregador & Motorista',
        descriptionKey: 'project.gti.app.desc',
        tags: [
          'React Native',
          'Expo 54',
          'Expo Router',
          'TypeScript',
          'React Query',
          'Camera',
          'SecureStore',
        ],
        roleKey: 'project.gti.app.role',
        featuresKey: 'project.gti.app.features',
      },
    ],
  },
  {
    title: 'Meu Acesso',
    descriptionKey: 'project.meuacesso.desc',
    featured: true,
    year: 2025,
    month: 12,
    projectType: 'landing',
    platformType: 'web',
    images: [
      '/projects/meuacesso/1.png',
      '/projects/meuacesso/2.png',
      '/projects/meuacesso/3.png',
      '/projects/meuacesso/4.png',
      '/projects/meuacesso/5.png',
      '/projects/meuacesso/6.png',
      '/projects/meuacesso/7.png',
      '/projects/meuacesso/8.png',
    ],
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'Styled-Components',
      'Framer Motion',
      'Credit Card UI',
    ],
    roleKey: 'project.meuacesso.role',
    durationKey: 'project.meuacesso.duration',
    highlightKey: 'project.meuacesso.highlight',
  },
];

export const PERSONAL_PROJECTS: ProjectItem[] = [
  {
    title: 'ElevenLabs',
    descriptionKey: 'project.elevenlabs.desc',
    year: 2025,
    month: 9,
    projectType: 'landing',
    platformType: 'web',
    images: [
      '/projects/eleven-labs.jpg',
      '/projects/eleven-labs2.jpg',
      '/projects/eleven-labs3.jpg',
      '/projects/eleven-labs4.jpg',
      '/projects/eleven-labs6.jpg',
    ],
    tags: [
      'Next.js',
      'React',
      'TypeScript',
      'JavaScript',
      'JSX',
      'HTML',
      'CSS',
      'Styled-Components',
    ],
    link: 'https://project-eleven-lab.vercel.app/conversational-ai/dashboard',
  },
  {
    title: 'Portfólio v1',
    descriptionKey: 'project.portfolio.desc',
    year: 2024,
    month: 3,
    projectType: 'landing',
    platformType: 'web',
    images: [
      '/projects/first-portfolio.png',
      '/projects/first-portfolio2.png',
      '/projects/first-portfolio3.png',
      '/projects/first-portfolio4.png',
    ],
    tags: ['JavaScript', 'HTML', 'CSS'],
    link: 'https://arthurramoz.github.io/Portfolio-1/index.html',
  },
  {
    title: 'Paragrafeado',
    descriptionKey: 'project.paragrafeado.desc',
    year: 2023,
    month: 8,
    projectType: 'other',
    platformType: 'web',
    images: ['/projects/paragrafeado.png'],
    tags: ['React', 'JavaScript', 'JSX', 'HTML', 'CSS'],
    link: 'https://arthurramoz.github.io/paragrafeado-react/',
  },
];

export const UNIVERSITY_PROJECTS: ProjectItem[] = [
  {
    title: 'Netflix CRUD',
    descriptionKey: 'project.netflix.desc',
    year: 2023,
    month: 6,
    projectType: 'other',
    platformType: 'web',
    images: ['/projects/netflix.jpg'],
    tags: ['JavaScript', 'JQuery', 'PHP', 'MySQL', 'HTML', 'CSS'],
  },
  {
    title: 'Super Calculadora C',
    descriptionKey: 'project.calculadora.desc',
    year: 2023,
    month: 4,
    projectType: 'other',
    platformType: 'web',
    tags: ['C'],
  },
];

export const ALL_PROJECTS: ProjectItem[] = [
  ...COMPANY_PROJECTS,
  ...PERSONAL_PROJECTS,
  ...UNIVERSITY_PROJECTS,
].sort((a, b) => {
  const dateA = a.year * 100 + (a.month ?? 0);
  const dateB = b.year * 100 + (b.month ?? 0);
  return dateB - dateA;
});
