import { IconType } from 'react-icons';
import {
  FiBookOpen,
  FiBriefcase,
  FiCode,
  FiGlobe,
  FiAward,
  FiLayers,
  FiMonitor,
  FiShoppingCart,
  FiServer,
  FiTrendingUp,
} from 'react-icons/fi';

export type TimelineCategory = 'education' | 'work' | 'freelance' | 'milestone';

export interface TimelineEntry {
  id: string;
  category: TimelineCategory;
  icon?: IconType;
  year: number;
  month?: number;
  titleKey: string;
  descriptionKey: string;
  tags?: string[];
  highlight?: boolean;
}

export const TIMELINE_ENTRIES: TimelineEntry[] = [
  {
    id: '2026-projects-company',
    category: 'work',
    icon: FiBriefcase,
    year: 2026,
    titleKey: 'timeline.2026.projects',
    descriptionKey: 'timeline.2026.projects.desc',
    tags: ['16+ Projetos', 'Front-End', 'B2B', 'B2C'],
    highlight: true,
  },
  {
    id: '2026-fullstack-study',
    category: 'education',
    icon: FiServer,
    year: 2026,
    titleKey: 'timeline.2026.fullstack',
    descriptionKey: 'timeline.2026.fullstack.desc',
    tags: ['SaaS', 'Full Stack', 'Strapi', 'SSH', 'Prisma', 'GitHub'],
    highlight: true,
  },
  {
    id: '2026-english',
    category: 'education',
    icon: FiGlobe,
    year: 2026,
    titleKey: 'timeline.2026.english',
    descriptionKey: 'timeline.2026.english.desc',
    tags: ['Inglês B2'],
  },
  {
    id: '2025-heavy-stack',
    category: 'education',
    icon: FiLayers,
    year: 2025,
    titleKey: 'timeline.2025.stack',
    descriptionKey: 'timeline.2025.stack.desc',
    tags: ['Node.js', 'Backend', 'Pagar.me', 'Firebase', 'WebSockets', 'SaaS'],
    highlight: true,
  },
  {
    id: '2025-hired-junior',
    category: 'work',
    icon: FiTrendingUp,
    year: 2025,
    month: 10,
    titleKey: 'timeline.2025.hired',
    descriptionKey: 'timeline.2025.hired.desc',
    tags: ['Front-End Junior', 'Efetivado'],
    highlight: true,
  },
  {
    id: '2025-freela-done',
    category: 'freelance',
    icon: FiGlobe,
    year: 2025,
    titleKey: 'timeline.2025.freela',
    descriptionKey: 'timeline.2025.freela.desc',
    tags: ['Freelance', 'Projeto Finalizado'],
    highlight: true,
  },
  {
    id: '2025-english',
    category: 'education',
    icon: FiGlobe,
    year: 2025,
    titleKey: 'timeline.2025.english',
    descriptionKey: 'timeline.2025.english.desc',
    tags: ['Inglês B2'],
  },
  {
    id: '2024-mestres-intern',
    category: 'work',
    icon: FiBriefcase,
    year: 2024,
    month: 10,
    titleKey: 'timeline.2024.intern',
    descriptionKey: 'timeline.2024.intern.desc',
    tags: ['Mestres da Web', 'Estágio', 'Front-End'],
    highlight: true,
  },
  {
    id: '2024-study-stack',
    category: 'education',
    icon: FiCode,
    year: 2024,
    titleKey: 'timeline.2024.stack',
    descriptionKey: 'timeline.2024.stack.desc',
    tags: ['JS', 'TS', 'React', 'Next.js', 'REST API', 'Figma', 'Git'],
    highlight: true,
  },
  {
    id: '2024-freela-upwork',
    category: 'freelance',
    icon: FiGlobe,
    year: 2024,
    titleKey: 'timeline.2024.freela',
    descriptionKey: 'timeline.2024.freela.desc',
    tags: ['Upwork', 'Freelance', 'Primeiro Projeto'],
    highlight: true,
  },
  {
    id: '2024-courses-done',
    category: 'milestone',
    icon: FiAward,
    year: 2024,
    titleKey: 'timeline.2024.courses',
    descriptionKey: 'timeline.2024.courses.desc',
    tags: ['Certificações'],
  },
  {
    id: '2024-english',
    category: 'education',
    icon: FiGlobe,
    year: 2024,
    titleKey: 'timeline.2024.english',
    descriptionKey: 'timeline.2024.english.desc',
    tags: ['Inglês B1'],
  },
  {
    id: '2023-fatec',
    category: 'education',
    icon: FiBookOpen,
    year: 2023,
    titleKey: 'timeline.2023.fatec',
    descriptionKey: 'timeline.2023.fatec.desc',
    tags: ['FATEC MC', 'ADS'],
    highlight: true,
  },
  {
    id: '2023-courses-done',
    category: 'milestone',
    icon: FiAward,
    year: 2023,
    titleKey: 'timeline.2023.courses',
    descriptionKey: 'timeline.2023.courses.desc',
    tags: ['Cursos Finalizados'],
  },
  {
    id: '2023-study-frameworks',
    category: 'education',
    icon: FiCode,
    year: 2023,
    titleKey: 'timeline.2023.frameworks',
    descriptionKey: 'timeline.2023.frameworks.desc',
    tags: ['Bootstrap', 'jQuery', 'React', 'JavaScript'],
    highlight: true,
  },
  {
    id: '2023-english',
    category: 'education',
    icon: FiGlobe,
    year: 2023,
    titleKey: 'timeline.2023.english',
    descriptionKey: 'timeline.2023.english.desc',
    tags: ['Inglês A2'],
  },
  {
    id: '2022-first-code',
    category: 'milestone',
    icon: FiCode,
    year: 2022,
    titleKey: 'timeline.2022.code',
    descriptionKey: 'timeline.2022.code.desc',
    tags: ['HTML', 'CSS', 'JavaScript'],
    highlight: true,
  },
  {
    id: '2022-danki-code',
    category: 'education',
    icon: FiMonitor,
    year: 2022,
    titleKey: 'timeline.2022.danki',
    descriptionKey: 'timeline.2022.danki.desc',
    tags: ['Front-End Completo', 'Web Design Express', 'Dev Web Completo'],
    highlight: true,
  },
  {
    id: '2022-english',
    category: 'education',
    icon: FiGlobe,
    year: 2022,
    titleKey: 'timeline.2022.english',
    descriptionKey: 'timeline.2022.english.desc',
    tags: ['Cultura Inglesa', 'Inglês A1'],
    highlight: true,
  },
  {
    id: '2021-first-project-sold',
    category: 'milestone',
    icon: FiShoppingCart,
    year: 2021,
    titleKey: 'timeline.2021.sold',
    descriptionKey: 'timeline.2021.sold.desc',
    tags: ['WordPress', 'Elementor', 'HostGator'],
    highlight: true,
  },
  {
    id: '2021-shopify',
    category: 'education',
    icon: FiShoppingCart,
    year: 2021,
    titleKey: 'timeline.2021.shopify',
    descriptionKey: 'timeline.2021.shopify.desc',
    tags: ['Shopify', 'E-commerce'],
    highlight: true,
  },
  {
    id: '2020-wordpress',
    category: 'education',
    icon: FiGlobe,
    year: 2020,
    titleKey: 'timeline.2020.wordpress',
    descriptionKey: 'timeline.2020.wordpress.desc',
    tags: ['WordPress', 'Elementor'],
    highlight: true,
  },
  {
    id: '2020-hosting',
    category: 'education',
    icon: FiServer,
    year: 2020,
    titleKey: 'timeline.2020.hosting',
    descriptionKey: 'timeline.2020.hosting.desc',
    tags: ['SSH', 'Domínios', 'Hospedagens'],
    highlight: true,
  },
  {
    id: '2020-webdesign',
    category: 'education',
    icon: FiMonitor,
    year: 2020,
    titleKey: 'timeline.2020.webdesign',
    descriptionKey: 'timeline.2020.webdesign.desc',
    tags: ['Web Design', 'UI Concepts'],
    highlight: true,
  },
];

export const CATEGORY_COLORS: Record<TimelineCategory, string> = {
  education: '#48cae4',
  work: '#7b68ee',
  freelance: '#fb6f92',
  milestone: '#f9c74f',
};
