import { Language } from '@/contexts/LanguageContext';

export interface VersionEntry {
  version: string;
  date: string;
  label: string;
  highlights: Record<Exclude<Language, 'es'>, string[]> & { es?: string[] };
}

export const CURRENT_VERSION = 'v1.8';
export const CURRENT_LABEL = 'Nova';

export const VERSION_HISTORY: VersionEntry[] = [
  {
    version: 'v1.8',
    date: '21/05/2026',
    label: 'Nova',
    highlights: {
      pt: [
        'Cursor personalizado (dot + ring) com efeito magnético em hover — substitui o cursor nativo no desktop',
        'Sombra do cursor (CursorGlow) mais fluida e sutil com delay aumentado',
        'Topbar reestruturada com dropdowns de Portfólio e Sobre Mim',
        'Estudos de caso: Integração Pagar.me v5 e Chat em tempo real com Firebase',
        'Página de depoimentos com estado vazio (EmptyState)',
        'Bandeira do idioma atual exibida ao lado da engrenagem na topbar',
        'Remoção do subtítulo "Software Engineer & Full Stack" do Hero',
        'Cor do cursor adapta ao tema (branco no escuro, preto no claro)',
      ],
      en: [
        'Custom cursor (dot + ring) with magnetic hover effect — replaces native cursor on desktop',
        'Cursor glow made more fluid and subtle with increased delay',
        'Topbar restructured with Portfolio and About Me dropdowns',
        'Case studies: Pagar.me v5 Integration and Realtime Chat with Firebase',
        'Testimonials page with empty state (EmptyState)',
        'Current language flag displayed beside settings gear in topbar',
        'Removed "Software Engineer & Full Stack" subtitle from Hero',
        'Cursor color adapts to theme (white on dark, black on light)',
      ],
      fr: [
        'Curseur personnalisé (point + anneau) avec effet magnétique au survol — remplace le curseur natif sur desktop',
        'Lueur du curseur plus fluide et subtile avec délai augmenté',
        'Topbar restructurée avec dropdowns Portfólio et À propos',
        'Études de cas : Intégration Pagar.me v5 et Chat temps réel avec Firebase',
        'Page témoignages avec état vide (EmptyState)',
        'Drapeau de la langue actuelle affiché à côté de l\'engrenage dans la topbar',
        'Suppression du sous-titre "Software Engineer & Full Stack" du Hero',
        'Couleur du curseur s\'adapte au thème (blanc sur sombre, noir sur clair)',
      ],
      ru: [
        'Кастомный курсор (точка + кольцо) с магнитным эффектом при наведении — заменяет нативный курсор на десктопе',
        'Свечение курсора стало более плавным и тонким с увеличенной задержкой',
        'Topbar реструктурирован с dropdown-меню Портфолио и Обо мне',
        'Кейсы: Интеграция Pagar.me v5 и Чат в реальном времени с Firebase',
        'Страница отзывов с пустым состоянием (EmptyState)',
        'Флаг текущего языка отображается рядом с шестерёнкой в topbar',
        'Удалён подзаголовок "Software Engineer & Full Stack" из Hero',
        'Цвет курсора адаптируется к теме (белый на тёмной, чёрный на светлой)',
      ],
      es: [
        'Cursor personalizado (punto + anillo) con efecto magnético en hover — reemplaza el cursor nativo en escritorio',
        'Sombra del cursor más fluida y sutil con mayor delay',
        'Topbar reestructurada con dropdowns de Portafolio y Sobre Mí',
        'Estudios de caso: Integración Pagar.me v5 y Chat en tiempo real con Firebase',
        'Página de testimonios con estado vacío (EmptyState)',
        'Bandera del idioma actual mostrada junto al engranaje en la topbar',
        'Eliminación del subtítulo "Software Engineer & Full Stack" del Hero',
        'Color del cursor se adapta al tema (blanco en oscuro, negro en claro)',
      ],
    },
  },
  {
    version: 'v1.6',
    date: '29/04/2026',
    label: 'Pulse',
    highlights: {
      pt: [
        'Nova página de Habilidades com círculos estilizados e logos de cada tecnologia',
        'Layout escalonado em duas fileiras com auto-scroll a cada 5 segundos',
        'Hover nos círculos revela o nome da stack com overlay blur',
        'Seção GitHub dedicada na Home com gráfico de contribuições e contagem total de commits',
        'Bio pessoal reescrita com foco em design, soft skills, hobbies e experiência com clientes',
        'Dados de skills centralizados em /config/skills.ts',
        'Link "Habilidades" adicionado na navbar, drawer mobile e footer',
        'Traduções completas (PT/EN/FR/RU/ES) para a página de Habilidades',
      ],
      en: [
        'New Skills page with stylized circles and tech logos',
        'Staggered two-row layout with auto-scroll every 5 seconds',
        'Hover on circles reveals stack name with blur overlay',
        'Dedicated GitHub section on Home with contribution graph and total commit count',
        'Personal bio rewritten focusing on design, soft skills, hobbies and client experience',
        'Skills data centralized in /config/skills.ts',
        '"Skills" link added to navbar, mobile drawer and footer',
        'Full translations (PT/EN/FR/RU/ES) for the Skills page',
      ],
      fr: [
        'Nouvelle page Compétences avec cercles stylisés et logos technologiques',
        'Mise en page décalée sur deux rangées avec défilement auto toutes les 5 secondes',
        'Survol des cercles révèle le nom du stack avec overlay flou',
        'Section GitHub dédiée sur la Home avec graphique de contributions et total de commits',
        'Bio personnelle réécrite axée sur le design, soft skills, hobbies et expérience client',
        'Données de compétences centralisées dans /config/skills.ts',
        'Lien "Compétences" ajouté à la navbar, drawer mobile et footer',
        'Traductions complètes (PT/EN/FR/RU/ES) pour la page Compétences',
      ],
      ru: [
        'Новая страница Навыки с стильными кругами и логотипами технологий',
        'Шахматная раскладка в два ряда с автопрокруткой каждые 5 секунд',
        'При наведении на круг отображается название стека с размытием',
        'Отдельная секция GitHub на главной с графиком вкладов и общим числом коммитов',
        'Личная биография переписана с фокусом на дизайн, soft skills, хобби и клиентский опыт',
        'Данные навыков централизованы в /config/skills.ts',
        'Ссылка "Навыки" добавлена в navbar, мобильный drawer и footer',
        'Полные переводы (PT/EN/FR/RU/ES) для страницы Навыки',
      ],
      es: [
        'Nueva página de Habilidades con círculos estilizados y logos de cada tecnología',
        'Diseño escalonado en dos filas con desplazamiento automático cada 5 segundos',
        'Hover en los círculos revela el nombre del stack con overlay blur',
        'Sección GitHub dedicada en Home con gráfico de contribuciones y total de commits',
        'Bio personal reescrita con enfoque en diseño, soft skills, hobbies y experiencia con clientes',
        'Datos de habilidades centralizados en /config/skills.ts',
        'Enlace "Habilidades" añadido a la navbar, drawer móvil y footer',
        'Traducciones completas (PT/EN/FR/RU/ES) para la página de Habilidades',
      ],
    },
  },
  {
    version: 'v1.5',
    date: '27/04/2026',
    label: 'Nexus',
    highlights: {
      pt: [
        'Nova página de Jornada — timeline interativa com categorias, ícones, tags e animações staggered',
        'Idioma Espanhol (ES) adicionado em todo o portfolio',
        'Padding global de páginas centralizado no theme.ts (pagePadding)',
        'Styled-components compartilhados extraídos para global.ts (PageWrapper, PageTag, PageHeading)',
        'Títulos azuis de seção (PageTag) adicionados em Configurações e Jornada',
        '"Jornada" adicionado à topbar desktop e drawer mobile',
        'Remoção de todos os comentários do código',
        'Largura das páginas Configurações e Jornada corrigida para 100% com max-width do tema',
        'Chaves de tradução curtas para tema (Claro / Escuro) no menu da navbar',
        'Timeline config dinâmica — eventos editáveis em /config/timeline.ts',
      ],
      en: [
        'New Journey page — interactive timeline with categories, icons, tags and staggered animations',
        'Spanish (ES) language added across the entire portfolio',
        'Global page padding centralized in theme.ts (pagePadding)',
        'Shared styled-components extracted to global.ts (PageWrapper, PageTag, PageHeading)',
        'Blue section tags (PageTag) added to Settings and Journey pages',
        '"Journey" link added to desktop topbar and mobile drawer',
        'All code comments removed',
        'Settings and Journey page width fixed to 100% with theme max-width',
        'Short translation keys for theme (Light / Dark) in navbar menu',
        'Dynamic timeline config — events editable in /config/timeline.ts',
      ],
      fr: [
        'Nouvelle page Parcours — timeline interactive avec catégories, icônes, tags et animations décalées',
        'Langue Espagnol (ES) ajoutée sur tout le portfolio',
        'Padding global des pages centralisé dans theme.ts (pagePadding)',
        'Styled-components partagés extraits vers global.ts (PageWrapper, PageTag, PageHeading)',
        'Tags de section bleus (PageTag) ajoutés sur Paramètres et Parcours',
        'Lien "Parcours" ajouté à la topbar desktop et au drawer mobile',
        'Tous les commentaires de code supprimés',
        'Largeur des pages Paramètres et Parcours corrigée à 100% avec max-width du thème',
        'Clés de traduction courtes pour le thème (Clair / Sombre) dans le menu navbar',
        'Config timeline dynamique — événements modifiables dans /config/timeline.ts',
      ],
      ru: [
        'Новая страница Путь — интерактивная timeline с категориями, иконками, тегами и каскадными анимациями',
        'Испанский язык (ES) добавлен по всему портфолио',
        'Глобальный padding страниц централизован в theme.ts (pagePadding)',
        'Общие styled-components вынесены в global.ts (PageWrapper, PageTag, PageHeading)',
        'Синие теги секций (PageTag) добавлены на страницы Настройки и Путь',
        'Ссылка "Путь" добавлена в desktop topbar и мобильный drawer',
        'Все комментарии из кода удалены',
        'Ширина страниц Настройки и Путь исправлена до 100% с max-width темы',
        'Короткие ключи перевода для темы (Светлая / Тёмная) в меню navbar',
        'Динамичный конфиг timeline — события редактируются в /config/timeline.ts',
      ],
      es: [
        'Nueva página Trayectoria — timeline interactiva con categorías, iconos, tags y animaciones escalonadas',
        'Idioma Español (ES) añadido en todo el portfolio',
        'Padding global de páginas centralizado en theme.ts (pagePadding)',
        'Styled-components compartidos extraídos a global.ts (PageWrapper, PageTag, PageHeading)',
        'Tags de sección azules (PageTag) añadidos en Configuración y Trayectoria',
        '"Trayectoria" añadido a la topbar escritorio y el drawer mobile',
        'Todos los comentarios del código eliminados',
        'Ancho de las páginas Configuración y Trayectoria corregido a 100% con max-width del tema',
        'Claves de traducción cortas para el tema (Claro / Oscuro) en el menú navbar',
        'Config de timeline dinámica — eventos editables en /config/timeline.ts',
      ],
    },
  },
  {
    version: 'v1.0',
    date: '24/04/2026',
    label: 'release',
    highlights: {
      pt: [
        'Responsividade global com breakpoints via theme.media (sm/md/lg/xl)',
        'Menu hamburguer mobile com drawer lateral animado',
        'Toggle dia/noite premium com sol, lua e estrelas',
        'Menu de idiomas colapsável no drawer mobile',
        'Suporte a Français (FR) e Русский (RU)',
        'Scroll bloqueado ao abrir drawer mobile',
        'GitHub Graph responsivo com cells reduzidos no mobile',
        'Hero, About, Experience, Gallery, Projects, Courses, Changelog e Footer adaptados',
      ],
      en: [
        'Global responsiveness with theme.media breakpoints (sm/md/lg/xl)',
        'Mobile hamburger menu with animated side drawer',
        'Premium day/night toggle with sun, moon and stars',
        'Collapsible language menu in mobile drawer',
        'French (FR) and Russian (RU) language support',
        'Scroll lock when mobile drawer is open',
        'Responsive GitHub Graph with reduced cells on mobile',
        'Hero, About, Experience, Gallery, Projects, Courses, Changelog and Footer adapted',
      ],
      fr: [
        'Responsivité globale avec breakpoints theme.media (sm/md/lg/xl)',
        'Menu hamburger mobile avec drawer latéral animé',
        'Toggle jour/nuit premium avec soleil, lune et étoiles',
        'Menu de langues repliable dans le drawer mobile',
        'Support du Français (FR) et du Russe (RU)',
        'Scroll bloqué à l\'ouverture du drawer mobile',
        'GitHub Graph responsive avec cellules réduites sur mobile',
        'Hero, About, Experience, Gallery, Projects, Courses, Changelog et Footer adaptés',
      ],
      ru: [
        'Глобальная адаптивность через theme.media breakpoints (sm/md/lg/xl)',
        'Мобильное гамбургер-меню с анимированным боковым drawer',
        'Премиум переключатель день/ночь с солнцем, луной и звёздами',
        'Сворачиваемое меню языков в мобильном drawer',
        'Поддержка Français (FR) и Русский (RU)',
        'Блокировка скролла при открытии мобильного drawer',
        'Адаптивный GitHub Graph с уменьшенными ячейками на мобильных',
        'Hero, About, Experience, Gallery, Projects, Courses, Changelog и Footer адаптированы',
      ],
    },
  },
  {
    version: 'v0.8',
    date: '24/04/2026',
    label: 'beta',
    highlights: {
      pt: [
        'Logo tipográfica AR com monograma gradiente na navbar',
        'Favicon SVG personalizado com identidade visual',
        'Dropdown de projetos premium com ícones, descrições e arrow',
        'Menu de definições redesenhado com glassmorphism e staggered animations',
        'Submenu lateral de idiomas com seleção direta (hover)',
        'Logo da página Under Development atualizada para SVG inline',
        'Suporte a seleção direta de idioma (preparado para multi-idiomas)',
      ],
      en: [
        'AR typographic logo with gradient monogram in navbar',
        'Custom SVG favicon with visual identity',
        'Premium projects dropdown with icons, descriptions and arrow',
        'Redesigned settings menu with glassmorphism and staggered animations',
        'Lateral language submenu with direct selection (hover)',
        'Under Development page logo updated to inline SVG',
        'Direct language selection support (prepared for multi-language)',
      ],
      fr: [
        'Logo typographique AR avec monogramme dégradé dans la navbar',
        'Favicon SVG personnalisé avec identité visuelle',
        'Menu déroulant projets premium avec icônes, descriptions et flèche',
        'Menu paramètres redessiné avec glassmorphisme et animations décalées',
        'Sous-menu latéral des langues avec sélection directe (survol)',
        'Logo de la page Under Development mise à jour en SVG inline',
        'Support de sélection directe de langue (préparé pour le multilingue)',
      ],
      ru: [
        'Типографский логотип AR с градиентной монограммой в навбаре',
        'Пользовательский SVG фавикон с фирменным стилем',
        'Премиум выпадающее меню проектов с иконками, описаниями и стрелкой',
        'Обновлённое меню настроек с glassmorphism и каскадными анимациями',
        'Боковое подменю языков с прямым выбором (при наведении)',
        'Логотип страницы Under Development обновлён до inline SVG',
        'Поддержка прямого выбора языка (подготовлено к мультиязычности)',
      ],
    },
  },
  {
    version: 'v0.7',
    date: '23/04/2026',
    label: 'beta',
    highlights: {
      pt: [
        'Página de cursos com 28 certificações',
        'Filtros collapsíveis por organização e competências',
        'Logos de plataformas (Udemy, Alura, Cisco, AWS, etc.)',
        'Paginação reutilizável (10 por página)',
        'Carrossel de imagens nos projetos com auto-play',
        'Dados de projetos e cursos centralizados em /config',
        'Traduções completas (PT/EN) para cursos e datas',
      ],
      en: [
        'Courses page with 28 certifications',
        'Collapsible filters by organization and skills',
        'Platform logos (Udemy, Alura, Cisco, AWS, etc.)',
        'Reusable pagination (10 per page)',
        'Project image carousel with auto-play',
        'Projects and courses data centralized in /config',
        'Full translations (PT/EN) for courses and dates',
      ],
      fr: [
        'Page de formations avec 28 certifications',
        'Filtres repliables par organisation et compétences',
        'Logos de plateformes (Udemy, Alura, Cisco, AWS, etc.)',
        'Pagination réutilisable (10 par page)',
        'Carrousel d\'images des projets avec lecture automatique',
        'Données des projets et formations centralisées dans /config',
        'Traductions complètes (PT/EN) pour formations et dates',
      ],
      ru: [
        'Страница курсов с 28 сертификатами',
        'Сворачиваемые фильтры по организации и навыкам',
        'Логотипы платформ (Udemy, Alura, Cisco, AWS и др.)',
        'Переиспользуемая пагинация (10 на страницу)',
        'Карусель изображений проектов с автовоспроизведением',
        'Данные проектов и курсов централизованы в /config',
        'Полные переводы (PT/EN) для курсов и дат',
      ],
    },
  },
  {
    version: 'v0.6',
    date: '23/04/2026',
    label: 'beta',
    highlights: {
      pt: [
        'Páginas de projetos (pessoais, empresa, faculdade)',
        'Página de changelog com timeline editorial',
        'Dropdown de projetos na topbar e footer',
        'Footer com navegação colapsável e histórico de versões',
        'Stats do About refatorados para array dinâmico',
      ],
      en: [
        'Project pages (personal, company, university)',
        'Changelog page with editorial timeline',
        'Projects dropdown in topbar and footer',
        'Footer with collapsible navigation and version history',
        'About stats refactored to dynamic array',
      ],
      fr: [
        'Pages de projets (personnels, entreprise, université)',
        'Page de changelog avec timeline éditoriale',
        'Menu déroulant projets dans la topbar et le footer',
        'Footer avec navigation repliable et historique des versions',
        'Stats du À propos refactorisés en tableau dynamique',
      ],
      ru: [
        'Страницы проектов (личные, компания, университет)',
        'Страница changelog с редакционной timeline',
        'Выпадающее меню проектов в topbar и footer',
        'Footer со сворачиваемой навигацией и историей версий',
        'Статистика About рефакторирована в динамический массив',
      ],
    },
  },
  {
    version: 'v0.5',
    date: '21/04/2026',
    label: 'beta',
    highlights: {
      pt: [
        'Footer completo com navegação, redes sociais e contato',
        'Galeria de fotos pessoais com grid responsivo',
        'Menu de definições com clique e badge de versão',
      ],
      en: [
        'Full footer with navigation, social media and contact',
        'Personal photo gallery with responsive grid',
        'Settings menu with click and version badge',
      ],
      fr: [
        'Footer complet avec navigation, réseaux sociaux et contact',
        'Galerie de photos personnelles avec grille responsive',
        'Menu paramètres avec clic et badge de version',
      ],
      ru: [
        'Полный footer с навигацией, соцсетями и контактами',
        'Галерея личных фотографий с адаптивной сеткой',
        'Меню настроек с кликом и бейджем версии',
      ],
    },
  },
  {
    version: 'v0.4',
    date: '18/04/2026',
    label: 'beta',
    highlights: {
      pt: [
        'Seção About com bio e cards de estatísticas',
        'Navbar com scroll tracking e animações',
        'Botão Prosseguir com scroll suave',
      ],
      en: [
        'About section with bio and stats cards',
        'Navbar with scroll tracking and animations',
        'Continue button with smooth scroll',
      ],
      fr: [
        'Section À propos avec bio et cartes de statistiques',
        'Navbar avec suivi du scroll et animations',
        'Bouton Continuer avec défilement fluide',
      ],
      ru: [
        'Секция About с биографией и карточками статистики',
        'Navbar с отслеживанием скролла и анимациями',
        'Кнопка Продолжить с плавной прокруткой',
      ],
    },
  },
  {
    version: 'v0.3',
    date: '14/04/2026',
    label: 'alpha',
    highlights: {
      pt: [
        'Dark mode e light mode com persistência',
        'Menu de definições (tema, idioma)',
        'Cores adaptáveis para botões e textos',
      ],
      en: [
        'Dark mode and light mode with persistence',
        'Settings menu (theme, language)',
        'Adaptive colors for buttons and text',
      ],
      fr: [
        'Mode sombre et clair avec persistance',
        'Menu paramètres (thème, langue)',
        'Couleurs adaptatives pour boutons et textes',
      ],
      ru: [
        'Тёмная и светлая тема с сохранением',
        'Меню настроек (тема, язык)',
        'Адаптивные цвета для кнопок и текстов',
      ],
    },
  },
  {
    version: 'v0.2',
    date: '10/04/2026',
    label: 'alpha',
    highlights: {
      pt: [
        'i18n: suporte PT-BR e EN-US com bandeiras',
        'Navbar e hero traduzidos dinamicamente',
      ],
      en: [
        'i18n: PT-BR and EN-US support with flags',
        'Navbar and hero dynamically translated',
      ],
      fr: [
        'i18n : support PT-BR et EN-US avec drapeaux',
        'Navbar et hero traduits dynamiquement',
      ],
      ru: [
        'i18n: поддержка PT-BR и EN-US с флагами',
        'Navbar и hero с динамическим переводом',
      ],
    },
  },
  {
    version: 'v0.1',
    date: '08/04/2026',
    label: 'alpha',
    highlights: {
      pt: [
        'Hero section com animações framer-motion',
        'Navbar glassmorphism com blobs animados',
        'Página Under Development com countdown',
        'Estrutura inicial Next.js + styled-components',
      ],
      en: [
        'Hero section with framer-motion animations',
        'Glassmorphism navbar with animated blobs',
        'Under Development page with countdown',
        'Initial Next.js + styled-components setup',
      ],
      fr: [
        'Section hero avec animations framer-motion',
        'Navbar glassmorphisme avec blobs animés',
        'Page Under Development avec compte à rebours',
        'Structure initiale Next.js + styled-components',
      ],
      ru: [
        'Секция hero с анимациями framer-motion',
        'Navbar glassmorphism с анимированными блобами',
        'Страница Under Development с обратным отсчётом',
        'Начальная структура Next.js + styled-components',
      ],
    },
  },
];
